create table workflow_taskfieldschema
(
    id              int auto_increment
        primary key,
    creator         varchar(64)    null,
    create_at       datetime(6)    not null,
    update_at       datetime(6)    not null,
    updated_by      varchar(64)    null,
    end_at          datetime(6)    null,
    is_deleted      tinyint(1)     not null,
    is_builtin      tinyint(1)     not null,
    is_readonly     tinyint(1)     not null,
    is_valid        tinyint(1)     not null,
    display         tinyint(1)     not null,
    source_type     varchar(32)    not null,
    source_uri      varchar(255)   null,
    api_instance_id int            null,
    kv_relation     varchar(64)    not null,
    type            varchar(32)    not null,
    `key`           varchar(255)   not null,
    name            varchar(64)    not null,
    layout          varchar(32)    not null,
    validate_type   varchar(32)    not null,
    show_type       int            not null,
    show_conditions longtext       not null,
    regex           varchar(64)    null,
    regex_config    varchar(255)   not null,
    custom_regex    varchar(128)   null,
    `desc`          varchar(128)   null,
    tips            varchar(128)   null,
    is_tips         tinyint(1)     not null,
    `default`       varchar(10000) null,
    choice          longtext       not null,
    related_fields  longtext       null,
    meta            longtext       not null,
    stage           varchar(64)    not null,
    sequence        int            not null,
    task_schema_id  int            not null,
    constraint workflow_taskfieldsc_task_schema_id_0b30729a_fk_workflow_
        foreign key (task_schema_id) references workflow_taskschema (id)
);

create index workflow_taskfieldschema_is_deleted_d4cc0b3d
    on workflow_taskfieldschema (is_deleted);

INSERT INTO bk_itsm.workflow_taskfieldschema (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, api_instance_id, kv_relation, type, `key`, name, layout, validate_type, show_type, show_conditions, regex, regex_config, custom_regex, `desc`, tips, is_tips, `default`, choice, related_fields, meta, stage, sequence, task_schema_id) VALUES (1, null, '2022-04-04 18:29:35.469579', '2022-04-04 18:29:35.469595', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 0, '{}', 'STRING', 'task_name', '任务名称', 'COL_12', 'REQUIRE', 1, '{}', 'EMPTY', '{}', '', '', '', 0, '', '[]', '{}', '{}', 'CREATE', 0, 1);
INSERT INTO bk_itsm.workflow_taskfieldschema (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, api_instance_id, kv_relation, type, `key`, name, layout, validate_type, show_type, show_conditions, regex, regex_config, custom_regex, `desc`, tips, is_tips, `default`, choice, related_fields, meta, stage, sequence, task_schema_id) VALUES (2, null, '2022-04-04 18:29:35.469700', '2022-04-04 18:29:35.469708', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 0, '{}', 'COMPLEX-MEMBERS', 'processors', '处理人', 'COL_12', 'REQUIRE', 1, '{}', 'EMPTY', '{}', '', '', '', 0, '', '[]', '{}', '{}', 'CREATE', 1, 1);
INSERT INTO bk_itsm.workflow_taskfieldschema (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, api_instance_id, kv_relation, type, `key`, name, layout, validate_type, show_type, show_conditions, regex, regex_config, custom_regex, `desc`, tips, is_tips, `default`, choice, related_fields, meta, stage, sequence, task_schema_id) VALUES (3, null, '2022-04-04 18:29:35.469810', '2022-04-04 18:29:35.469818', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 0, '{}', 'SOPS_TEMPLATE', 'sops_templates', '标准运维参数', 'COL_12', 'REQUIRE', 1, '{}', 'EMPTY', '{}', '', '', '', 0, '', '[]', '{}', '{}', 'CREATE', 2, 1);
INSERT INTO bk_itsm.workflow_taskfieldschema (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, api_instance_id, kv_relation, type, `key`, name, layout, validate_type, show_type, show_conditions, regex, regex_config, custom_regex, `desc`, tips, is_tips, `default`, choice, related_fields, meta, stage, sequence, task_schema_id) VALUES (4, null, '2022-04-04 18:29:35.469898', '2022-04-04 18:29:35.469904', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 0, '{}', 'STRING', 'executeTime', '执行时长（分钟）', 'COL_12', 'REQUIRE', 1, '{}', 'NON_NEGATIVE', '{}', '', '运维执行时长 (浮点数,单位是分钟)', '运维执行时长 (浮点数,单位是分钟)', 1, '', '[]', '{}', '{}', 'CONFIRM', 1, 1);
INSERT INTO bk_itsm.workflow_taskfieldschema (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, api_instance_id, kv_relation, type, `key`, name, layout, validate_type, show_type, show_conditions, regex, regex_config, custom_regex, `desc`, tips, is_tips, `default`, choice, related_fields, meta, stage, sequence, task_schema_id) VALUES (5, null, '2022-04-04 18:29:35.469983', '2022-04-04 18:29:35.469989', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 0, '{}', 'STRING', 'reviewNumerator', '停机比例', 'COL_12', 'OPTION', 1, '{}', 'NON_NEGATIVE', '{}', '', '停机比例(整型 0-100)', '停机比例(整型 0-100)', 1, '', '[]', '{}', '{}', 'CONFIRM', 2, 1);
INSERT INTO bk_itsm.workflow_taskfieldschema (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, api_instance_id, kv_relation, type, `key`, name, layout, validate_type, show_type, show_conditions, regex, regex_config, custom_regex, `desc`, tips, is_tips, `default`, choice, related_fields, meta, stage, sequence, task_schema_id) VALUES (6, null, '2022-04-04 18:29:35.470097', '2022-04-04 18:29:35.470104', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 0, '{}', 'RADIO', 'reviewIsShutdown', '是否停机发布', 'COL_12', 'REQUIRE', 1, '{}', 'EMPTY', '{}', '', '是否停机发布 (整型：0, 1)', '是否停机发布 (整型：0, 1)', 1, '0', '[{"key":"1","name":"\\u662f"},{"key":"0","name":"\\u5426"}]', '{}', '{}', 'CONFIRM', 3, 1);
INSERT INTO bk_itsm.workflow_taskfieldschema (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, api_instance_id, kv_relation, type, `key`, name, layout, validate_type, show_type, show_conditions, regex, regex_config, custom_regex, `desc`, tips, is_tips, `default`, choice, related_fields, meta, stage, sequence, task_schema_id) VALUES (7, null, '2022-04-04 18:29:35.470200', '2022-04-04 18:29:35.470206', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 0, '{}', 'STRING', 'reviewShutdownTime', '停机耗费时长（分钟）', 'COL_12', 'OPTION', 1, '{}', 'NON_NEGATIVE', '{}', '', '停机耗费时长 (浮点数)', '停机耗费时长 (浮点数)', 1, '0', '[]', '{}', '{}', 'CONFIRM', 4, 1);
INSERT INTO bk_itsm.workflow_taskfieldschema (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, api_instance_id, kv_relation, type, `key`, name, layout, validate_type, show_type, show_conditions, regex, regex_config, custom_regex, `desc`, tips, is_tips, `default`, choice, related_fields, meta, stage, sequence, task_schema_id) VALUES (8, null, '2022-04-04 18:29:35.470285', '2022-04-04 18:29:35.470291', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 0, '{}', 'STRING', 'prepareTime', '任务准备时长（分钟）', 'COL_12', 'REQUIRE', 1, '{}', 'NON_NEGATIVE', '{}', '', '任务准备时长 (浮点数,单位是分钟)', '任务准备时长 (浮点数,单位是分钟)', 1, '0', '[]', '{}', '{}', 'CONFIRM', 5, 1);
INSERT INTO bk_itsm.workflow_taskfieldschema (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, api_instance_id, kv_relation, type, `key`, name, layout, validate_type, show_type, show_conditions, regex, regex_config, custom_regex, `desc`, tips, is_tips, `default`, choice, related_fields, meta, stage, sequence, task_schema_id) VALUES (9, null, '2022-04-04 18:29:35.470369', '2022-04-04 18:29:35.470375', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 0, '{}', 'STRING', 'testTime', '现网测试时长（分钟）', 'COL_12', 'REQUIRE', 1, '{}', 'NON_NEGATIVE', '{}', '', '现网测试时长 (浮点数,单位是分钟)', '现网测试时长 (浮点数,单位是分钟)', 1, '0', '[]', '{}', '{}', 'CONFIRM', 6, 1);
INSERT INTO bk_itsm.workflow_taskfieldschema (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, api_instance_id, kv_relation, type, `key`, name, layout, validate_type, show_type, show_conditions, regex, regex_config, custom_regex, `desc`, tips, is_tips, `default`, choice, related_fields, meta, stage, sequence, task_schema_id) VALUES (10, null, '2022-04-04 18:29:35.470454', '2022-04-04 18:29:35.470460', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 0, '{}', 'SELECT', 'isSuccess', '发布实施结论', 'COL_12', 'REQUIRE', 1, '{}', 'EMPTY', '{}', '', '发布实施结论', '发布实施结论', 1, '1', '[{"key":"1","name":"\\u5b8c\\u5168\\u6210\\u529f"},{"key":"2","name":"\\u6210\\u529f\\u4f46\\u6709\\u95ee\\u9898"},{"key":"3","name":"\\u53d1\\u5e03\\u5931\\u8d25"}]', '{}', '{}', 'CONFIRM', 7, 1);
INSERT INTO bk_itsm.workflow_taskfieldschema (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, api_instance_id, kv_relation, type, `key`, name, layout, validate_type, show_type, show_conditions, regex, regex_config, custom_regex, `desc`, tips, is_tips, `default`, choice, related_fields, meta, stage, sequence, task_schema_id) VALUES (11, null, '2022-04-04 18:29:35.470542', '2022-04-04 18:29:35.470548', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 0, '{}', 'DATETIME', 'actualEndTime', '实际结束时间', 'COL_12', 'REQUIRE', 1, '{}', 'EMPTY', '{}', '', '实际结束时间，日期格式 ''yyyy-MM-dd hh:mm:ss''', '实际结束时间，日期格式 ''yyyy-MM-dd hh:mm:ss''', 1, '', '[]', '{}', '{}', 'CONFIRM', 8, 1);
INSERT INTO bk_itsm.workflow_taskfieldschema (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, api_instance_id, kv_relation, type, `key`, name, layout, validate_type, show_type, show_conditions, regex, regex_config, custom_regex, `desc`, tips, is_tips, `default`, choice, related_fields, meta, stage, sequence, task_schema_id) VALUES (12, null, '2022-04-04 18:29:35.470625', '2022-04-04 18:29:35.470631', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 0, '{}', 'DATETIME', 'actualBeginTime', '实际开始时间', 'COL_12', 'REQUIRE', 1, '{}', 'EMPTY', '{}', '', '实际开始时间，日期格式 ''yyyy-MM-dd hh:mm:ss''', '实际开始时间，日期格式 ''yyyy-MM-dd hh:mm:ss''', 1, '', '[]', '{}', '{}', 'CONFIRM', 9, 1);
INSERT INTO bk_itsm.workflow_taskfieldschema (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, api_instance_id, kv_relation, type, `key`, name, layout, validate_type, show_type, show_conditions, regex, regex_config, custom_regex, `desc`, tips, is_tips, `default`, choice, related_fields, meta, stage, sequence, task_schema_id) VALUES (13, null, '2022-04-04 18:29:35.470709', '2022-04-04 18:29:35.470715', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 0, '{}', 'RADIO', 'reviewIsDbChange', '是否DB发布', 'COL_12', 'REQUIRE', 1, '{}', 'EMPTY', '{}', '', '是否DB发布', '是否DB发布', 1, '0', '[{"key":"1","name":"\\u662f"},{"key":"0","name":"\\u5426"}]', '{}', '{}', 'CONFIRM', 10, 1);
INSERT INTO bk_itsm.workflow_taskfieldschema (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, api_instance_id, kv_relation, type, `key`, name, layout, validate_type, show_type, show_conditions, regex, regex_config, custom_regex, `desc`, tips, is_tips, `default`, choice, related_fields, meta, stage, sequence, task_schema_id) VALUES (14, null, '2022-04-04 18:29:35.470795', '2022-04-04 18:29:35.470801', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 0, '{}', 'STRING', 'reviewDbChangeTime', 'DB耗费时长（分钟）', 'COL_12', 'OPTION', 1, '{}', 'NON_NEGATIVE', '{}', '', 'DB耗费时长 (浮点数)', 'DB耗费时长 (浮点数)', 1, '0', '[]', '{}', '{}', 'CONFIRM', 11, 1);
INSERT INTO bk_itsm.workflow_taskfieldschema (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, api_instance_id, kv_relation, type, `key`, name, layout, validate_type, show_type, show_conditions, regex, regex_config, custom_regex, `desc`, tips, is_tips, `default`, choice, related_fields, meta, stage, sequence, task_schema_id) VALUES (15, null, '2022-04-04 18:29:35.470879', '2022-04-04 18:29:35.470884', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 0, '{}', 'TEXT', 'conclusion', '发布经验总结', 'COL_12', 'OPTION', 1, '{}', 'EMPTY', '{}', '', '发布经验总结', '', 0, '', '[]', '{}', '{}', 'CONFIRM', 12, 1);
INSERT INTO bk_itsm.workflow_taskfieldschema (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, api_instance_id, kv_relation, type, `key`, name, layout, validate_type, show_type, show_conditions, regex, regex_config, custom_regex, `desc`, tips, is_tips, `default`, choice, related_fields, meta, stage, sequence, task_schema_id) VALUES (16, null, '2022-04-04 18:29:35.470966', '2022-04-04 18:29:35.470972', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 0, '{}', 'STRING', 'dbBackupTime', 'DB备份时长（分钟）', 'COL_12', 'OPTION', 1, '{}', 'NON_NEGATIVE', '{}', '', '', '', 0, '', '[]', '{}', '{}', 'CONFIRM', 13, 1);
