create table auth_permission
(
    id              int auto_increment
        primary key,
    name            varchar(255) not null,
    content_type_id int          not null,
    codename        varchar(100) not null,
    constraint auth_permission_content_type_id_codename_01ab375a_uniq
        unique (content_type_id, codename),
    constraint auth_permission_content_type_id_2f476e4b_fk_django_co
        foreign key (content_type_id) references django_content_type (id)
);

INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (1, 'Can add log entry', 3, 'add_logentry');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (2, 'Can change log entry', 3, 'change_logentry');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (3, 'Can delete log entry', 3, 'delete_logentry');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (4, 'Can view log entry', 3, 'view_logentry');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (5, 'Can add permission', 4, 'add_permission');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (6, 'Can change permission', 4, 'change_permission');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (7, 'Can delete permission', 4, 'delete_permission');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (8, 'Can view permission', 4, 'view_permission');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (9, 'Can add group', 5, 'add_group');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (10, 'Can change group', 5, 'change_group');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (11, 'Can delete group', 5, 'delete_group');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (12, 'Can view group', 5, 'view_group');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (13, 'Can add content type', 6, 'add_contenttype');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (14, 'Can change content type', 6, 'change_contenttype');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (15, 'Can delete content type', 6, 'delete_contenttype');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (16, 'Can view content type', 6, 'view_contenttype');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (17, 'Can add session', 7, 'add_session');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (18, 'Can change session', 7, 'change_session');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (19, 'Can delete session', 7, 'delete_session');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (20, 'Can view session', 7, 'view_session');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (21, 'Can add site', 8, 'add_site');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (22, 'Can change site', 8, 'change_site');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (23, 'Can delete site', 8, 'delete_site');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (24, 'Can view site', 8, 'view_site');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (25, 'Can add user', 1, 'add_user');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (26, 'Can change user', 1, 'change_user');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (27, 'Can delete user', 1, 'delete_user');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (28, 'Can view user', 1, 'view_user');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (29, 'Can add user property', 9, 'add_userproperty');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (30, 'Can change user property', 9, 'change_userproperty');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (31, 'Can delete user property', 9, 'delete_userproperty');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (32, 'Can view user property', 9, 'view_userproperty');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (33, 'Can add user proxy', 2, 'add_userproxy');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (34, 'Can change user proxy', 2, 'change_userproxy');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (35, 'Can delete user proxy', 2, 'delete_userproxy');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (36, 'Can view user proxy', 2, 'view_userproxy');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (37, 'Can add verify info', 10, 'add_verifyinfo');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (38, 'Can change verify info', 10, 'change_verifyinfo');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (39, 'Can delete verify info', 10, 'delete_verifyinfo');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (40, 'Can view verify info', 10, 'view_verifyinfo');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (41, 'Can add 聚合操作', 11, 'add_aggregateaction');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (42, 'Can change 聚合操作', 11, 'change_aggregateaction');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (43, 'Can delete 聚合操作', 11, 'delete_aggregateaction');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (44, 'Can view 聚合操作', 11, 'view_aggregateaction');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (45, 'Can add 权限策略', 12, 'add_policy');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (46, 'Can change 权限策略', 12, 'change_policy');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (47, 'Can delete 权限策略', 12, 'delete_policy');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (48, 'Can view 权限策略', 12, 'view_policy');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (49, 'Can add 权限申请', 13, 'add_application');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (50, 'Can change 权限申请', 13, 'change_application');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (51, 'Can delete 权限申请', 13, 'delete_application');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (52, 'Can view 权限申请', 13, 'view_application');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (53, 'Can add 操作与审批流程关联', 14, 'add_actionprocessrelation');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (54, 'Can change 操作与审批流程关联', 14, 'change_actionprocessrelation');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (55, 'Can delete 操作与审批流程关联', 14, 'delete_actionprocessrelation');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (56, 'Can view 操作与审批流程关联', 14, 'view_actionprocessrelation');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (57, 'Can add 审批流程全局配置', 15, 'add_approvalprocessglobalconfig');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (58, 'Can change 审批流程全局配置', 15, 'change_approvalprocessglobalconfig');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (59, 'Can delete 审批流程全局配置', 15, 'delete_approvalprocessglobalconfig');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (60, 'Can view 审批流程全局配置', 15, 'view_approvalprocessglobalconfig');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (61, 'Can add 用户组与审批流程关联', 16, 'add_groupprocessrelation');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (62, 'Can change 用户组与审批流程关联', 16, 'change_groupprocessrelation');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (63, 'Can delete 用户组与审批流程关联', 16, 'delete_groupprocessrelation');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (64, 'Can view 用户组与审批流程关联', 16, 'view_groupprocessrelation');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (65, 'Can add 用户组', 17, 'add_group');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (66, 'Can change 用户组', 17, 'change_group');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (67, 'Can delete 用户组', 17, 'delete_group');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (68, 'Can view 用户组', 17, 'view_group');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (69, 'Can add 用户组授权锁', 18, 'add_groupauthorizelock');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (70, 'Can change 用户组授权锁', 18, 'change_groupauthorizelock');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (71, 'Can delete 用户组授权锁', 18, 'delete_groupauthorizelock');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (72, 'Can view 用户组授权锁', 18, 'view_groupauthorizelock');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (73, 'Can add 用户组SaaS属性', 19, 'add_groupsaasattribute');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (74, 'Can change 用户组SaaS属性', 19, 'change_groupsaasattribute');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (75, 'Can delete 用户组SaaS属性', 19, 'delete_groupsaasattribute');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (76, 'Can view 用户组SaaS属性', 19, 'view_groupsaasattribute');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (77, 'Can add 权限模板', 20, 'add_permtemplate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (78, 'Can change 权限模板', 20, 'change_permtemplate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (79, 'Can delete 权限模板', 20, 'delete_permtemplate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (80, 'Can view 权限模板', 20, 'view_permtemplate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (81, 'Can add 权限模板授权', 21, 'add_permtemplatepolicyauthorized');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (82, 'Can change 权限模板授权', 21, 'change_permtemplatepolicyauthorized');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (83, 'Can delete 权限模板授权', 21, 'delete_permtemplatepolicyauthorized');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (84, 'Can view 权限模板授权', 21, 'view_permtemplatepolicyauthorized');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (85, 'Can add 权限模板', 22, 'add_oldpermtemplate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (86, 'Can change 权限模板', 22, 'change_oldpermtemplate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (87, 'Can delete 权限模板', 22, 'delete_oldpermtemplate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (88, 'Can view 权限模板', 22, 'view_oldpermtemplate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (89, 'Can add 权限模板策略', 23, 'add_oldpermtemplatepolicy');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (90, 'Can change 权限模板策略', 23, 'change_oldpermtemplatepolicy');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (91, 'Can delete 权限模板策略', 23, 'delete_oldpermtemplatepolicy');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (92, 'Can view 权限模板策略', 23, 'view_oldpermtemplatepolicy');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (93, 'Can add 权限模板授权', 24, 'add_oldpermtemplatepolicyauthorized');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (94, 'Can change 权限模板授权', 24, 'change_oldpermtemplatepolicyauthorized');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (95, 'Can delete 权限模板授权', 24, 'delete_oldpermtemplatepolicyauthorized');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (96, 'Can view 权限模板授权', 24, 'view_oldpermtemplatepolicyauthorized');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (97, 'Can add 权限模板更新预提交', 25, 'add_permtemplatepreupdatelock');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (98, 'Can change 权限模板更新预提交', 25, 'change_permtemplatepreupdatelock');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (99, 'Can delete 权限模板更新预提交', 25, 'delete_permtemplatepreupdatelock');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (100, 'Can view 权限模板更新预提交', 25, 'view_permtemplatepreupdatelock');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (101, 'Can add 权限模板更新用户组同步预提交', 26, 'add_permtemplatepregroupsync');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (102, 'Can change 权限模板更新用户组同步预提交', 26, 'change_permtemplatepregroupsync');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (103, 'Can delete 权限模板更新用户组同步预提交', 26, 'delete_permtemplatepregroupsync');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (104, 'Can view 权限模板更新用户组同步预提交', 26, 'view_permtemplatepregroupsync');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (105, 'Can add category', 27, 'add_category');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (106, 'Can change category', 27, 'change_category');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (107, 'Can delete category', 27, 'delete_category');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (108, 'Can view category', 27, 'view_category');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (109, 'Can add department member', 28, 'add_departmentmember');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (110, 'Can change department member', 28, 'change_departmentmember');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (111, 'Can delete department member', 28, 'delete_departmentmember');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (112, 'Can view department member', 28, 'view_departmentmember');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (113, 'Can add 用户信息', 29, 'add_user');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (114, 'Can change 用户信息', 29, 'change_user');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (115, 'Can delete 用户信息', 29, 'delete_user');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (116, 'Can view 用户信息', 29, 'view_user');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (117, 'Can add user leader', 30, 'add_userleader');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (118, 'Can change user leader', 30, 'change_userleader');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (119, 'Can delete user leader', 30, 'delete_userleader');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (120, 'Can view user leader', 30, 'view_userleader');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (121, 'Can add 部门表', 31, 'add_department');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (122, 'Can change 部门表', 31, 'change_department');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (123, 'Can delete 部门表', 31, 'delete_department');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (124, 'Can view 部门表', 31, 'view_department');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (125, 'Can add sync record', 32, 'add_syncrecord');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (126, 'Can change sync record', 32, 'change_syncrecord');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (127, 'Can delete sync record', 32, 'delete_syncrecord');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (128, 'Can view sync record', 32, 'view_syncrecord');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (129, 'Can add 授权API白名单配置', 33, 'add_authapiallowlistconfig');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (130, 'Can change 授权API白名单配置', 33, 'change_authapiallowlistconfig');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (131, 'Can delete 授权API白名单配置', 33, 'delete_authapiallowlistconfig');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (132, 'Can view 授权API白名单配置', 33, 'view_authapiallowlistconfig');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (133, 'Can add 管理类API允许系统白名单', 34, 'add_managementapiallowlistconfig');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (134, 'Can change 管理类API允许系统白名单', 34, 'change_managementapiallowlistconfig');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (135, 'Can delete 管理类API允许系统白名单', 34, 'delete_managementapiallowlistconfig');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (136, 'Can view 管理类API允许系统白名单', 34, 'view_managementapiallowlistconfig');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (137, 'Can add 系统允许授权的系统', 35, 'add_systemallowauthsystem');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (138, 'Can change 系统允许授权的系统', 35, 'change_systemallowauthsystem');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (139, 'Can delete 系统允许授权的系统', 35, 'delete_systemallowauthsystem');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (140, 'Can view 系统允许授权的系统', 35, 'view_systemallowauthsystem');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (141, 'Can add 权限', 36, 'add_permission');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (142, 'Can change 权限', 36, 'change_permission');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (143, 'Can delete 权限', 36, 'delete_permission');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (144, 'Can view 权限', 36, 'view_permission');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (145, 'Can add 角色', 37, 'add_role');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (146, 'Can change 角色', 37, 'change_role');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (147, 'Can delete 角色', 37, 'delete_role');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (148, 'Can view 角色', 37, 'view_role');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (149, 'Can add 角色的权限', 38, 'add_roleperm');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (150, 'Can change 角色的权限', 38, 'change_roleperm');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (151, 'Can delete 角色的权限', 38, 'delete_roleperm');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (152, 'Can view 角色的权限', 38, 'view_roleperm');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (153, 'Can add 角色关联资源', 39, 'add_rolerelatedobject');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (154, 'Can change 角色关联资源', 39, 'change_rolerelatedobject');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (155, 'Can delete 角色关联资源', 39, 'delete_rolerelatedobject');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (156, 'Can view 角色关联资源', 39, 'view_rolerelatedobject');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (157, 'Can add 角色的限制范围', 40, 'add_rolescope');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (158, 'Can change 角色的限制范围', 40, 'change_rolescope');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (159, 'Can delete 角色的限制范围', 40, 'delete_rolescope');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (160, 'Can view 角色的限制范围', 40, 'view_rolescope');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (161, 'Can add 角色的用户', 41, 'add_roleuser');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (162, 'Can change 角色的用户', 41, 'change_roleuser');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (163, 'Can delete 角色的用户', 41, 'delete_roleuser');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (164, 'Can view 角色的用户', 41, 'view_roleuser');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (165, 'Can add subject限制', 42, 'add_scopesubject');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (166, 'Can change subject限制', 42, 'change_scopesubject');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (167, 'Can delete subject限制', 42, 'delete_scopesubject');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (168, 'Can view subject限制', 42, 'view_scopesubject');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (169, 'Can add role user system permission', 43, 'add_roleusersystempermission');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (170, 'Can change role user system permission', 43, 'change_roleusersystempermission');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (171, 'Can delete role user system permission', 43, 'delete_roleusersystempermission');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (172, 'Can view role user system permission', 43, 'view_roleusersystempermission');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (173, 'Can add 角色常用操作', 44, 'add_rolecommonaction');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (174, 'Can change 角色常用操作', 44, 'change_rolecommonaction');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (175, 'Can delete 角色常用操作', 44, 'delete_rolecommonaction');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (176, 'Can view 角色常用操作', 44, 'view_rolecommonaction');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (177, 'Can add role source', 45, 'add_rolesource');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (178, 'Can change role source', 45, 'change_rolesource');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (179, 'Can delete role source', 45, 'delete_rolesource');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (180, 'Can view role source', 45, 'view_rolesource');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (181, 'Can add 用户配置', 46, 'add_userprofile');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (182, 'Can change 用户配置', 46, 'change_userprofile');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (183, 'Can delete 用户配置', 46, 'delete_userprofile');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (184, 'Can view 用户配置', 46, 'view_userprofile');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (185, 'Can add 页面接入建模数据', 47, 'add_mocksystemmodel');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (186, 'Can change 页面接入建模数据', 47, 'change_mocksystemmodel');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (187, 'Can delete 页面接入建模数据', 47, 'delete_mocksystemmodel');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (188, 'Can view 页面接入建模数据', 47, 'view_mocksystemmodel');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (189, 'Can add 子任务状态', 48, 'add_subtaskstate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (190, 'Can change 子任务状态', 48, 'change_subtaskstate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (191, 'Can delete 子任务状态', 48, 'delete_subtaskstate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (192, 'Can view 子任务状态', 48, 'view_subtaskstate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (193, 'Can add 长时任务', 49, 'add_taskdetail');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (194, 'Can change 长时任务', 49, 'change_taskdetail');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (195, 'Can delete 长时任务', 49, 'delete_taskdetail');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (196, 'Can view 长时任务', 49, 'view_taskdetail');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (197, 'Can add event for meta', 50, 'add_eventformeta');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (198, 'Can change event for meta', 50, 'change_eventformeta');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (199, 'Can delete event for meta', 50, 'delete_eventformeta');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (200, 'Can view event for meta', 50, 'view_eventformeta');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (201, 'Can add 权限模板策略缓存', 51, 'add_permtemplatepoliciescache');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (202, 'Can change 权限模板策略缓存', 51, 'change_permtemplatepoliciescache');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (203, 'Can delete 权限模板策略缓存', 51, 'delete_permtemplatepoliciescache');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (204, 'Can view 权限模板策略缓存', 51, 'view_permtemplatepoliciescache');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (205, 'Can add crontab', 52, 'add_crontabschedule');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (206, 'Can change crontab', 52, 'change_crontabschedule');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (207, 'Can delete crontab', 52, 'delete_crontabschedule');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (208, 'Can view crontab', 52, 'view_crontabschedule');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (209, 'Can add interval', 53, 'add_intervalschedule');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (210, 'Can change interval', 53, 'change_intervalschedule');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (211, 'Can delete interval', 53, 'delete_intervalschedule');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (212, 'Can view interval', 53, 'view_intervalschedule');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (213, 'Can add periodic task', 54, 'add_periodictask');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (214, 'Can change periodic task', 54, 'change_periodictask');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (215, 'Can delete periodic task', 54, 'delete_periodictask');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (216, 'Can view periodic task', 54, 'view_periodictask');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (217, 'Can add periodic tasks', 55, 'add_periodictasks');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (218, 'Can change periodic tasks', 55, 'change_periodictasks');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (219, 'Can delete periodic tasks', 55, 'delete_periodictasks');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (220, 'Can view periodic tasks', 55, 'view_periodictasks');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (221, 'Can add task state', 56, 'add_taskmeta');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (222, 'Can change task state', 56, 'change_taskmeta');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (223, 'Can delete task state', 56, 'delete_taskmeta');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (224, 'Can view task state', 56, 'view_taskmeta');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (225, 'Can add saved group result', 57, 'add_tasksetmeta');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (226, 'Can change saved group result', 57, 'change_tasksetmeta');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (227, 'Can delete saved group result', 57, 'delete_tasksetmeta');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (228, 'Can view saved group result', 57, 'view_tasksetmeta');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (229, 'Can add task', 58, 'add_taskstate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (230, 'Can change task', 58, 'change_taskstate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (231, 'Can delete task', 58, 'delete_taskstate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (232, 'Can view task', 58, 'view_taskstate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (233, 'Can add worker', 59, 'add_workerstate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (234, 'Can change worker', 59, 'change_workerstate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (235, 'Can delete worker', 59, 'delete_workerstate');
INSERT INTO bk_iam.auth_permission (id, name, content_type_id, codename) VALUES (236, 'Can view worker', 59, 'view_workerstate');
