create table auth_permission
(
    id              int auto_increment
        primary key,
    name            varchar(255) not null,
    content_type_id int          not null,
    codename        varchar(100) not null,
    constraint auth_permission_content_type_id_codename_01ab375a_uniq
        unique (content_type_id, codename),
    constraint auth_permission_content_type_id_2f476e4b_fk_django_co
        foreign key (content_type_id) references django_content_type (id)
);

INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (4, 'Can add permission', 2, 'add_permission');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (5, 'Can change permission', 2, 'change_permission');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (6, 'Can delete permission', 2, 'delete_permission');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (7, 'Can add group', 3, 'add_group');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (8, 'Can change group', 3, 'change_group');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (9, 'Can delete group', 3, 'delete_group');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (10, 'Can add content type', 4, 'add_contenttype');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (11, 'Can change content type', 4, 'change_contenttype');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (12, 'Can delete content type', 4, 'delete_contenttype');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (13, 'Can add session', 5, 'add_session');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (14, 'Can change session', 5, 'change_session');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (15, 'Can delete session', 5, 'delete_session');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (16, 'Can add site', 6, 'add_site');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (17, 'Can change site', 6, 'change_site');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (18, 'Can delete site', 6, 'delete_site');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (19, 'Can add user', 7, 'add_user');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (20, 'Can change user', 7, 'change_user');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (21, 'Can delete user', 7, 'delete_user');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (22, 'Can add user property', 8, 'add_userproperty');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (23, 'Can change user property', 8, 'change_userproperty');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (24, 'Can delete user property', 8, 'delete_userproperty');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (25, 'Can add user proxy', 7, 'add_userproxy');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (26, 'Can change user proxy', 7, 'change_userproxy');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (27, 'Can delete user proxy', 7, 'delete_userproxy');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (28, 'Can add verify info', 9, 'add_verifyinfo');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (29, 'Can change verify info', 9, 'change_verifyinfo');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (30, 'Can delete verify info', 9, 'delete_verifyinfo');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (31, 'Can add 通知模板', 11, 'add_customnotice');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (32, 'Can change 通知模板', 11, 'change_customnotice');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (33, 'Can delete 通知模板', 11, 'delete_customnotice');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (34, 'Can add 系统设置', 12, 'add_systemsettings');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (35, 'Can change 系统设置', 12, 'change_systemsettings');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (36, 'Can delete 系统设置', 12, 'delete_systemsettings');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (37, 'Can add 数据迁移日志', 13, 'add_migratelogs');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (38, 'Can change 数据迁移日志', 13, 'change_migratelogs');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (39, 'Can delete 数据迁移日志', 13, 'delete_migratelogs');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (40, 'Can add 数据存储', 14, 'add_data');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (41, 'Can change 数据存储', 14, 'change_data');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (42, 'Can delete 数据存储', 14, 'delete_data');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (43, 'Can add 版本日志', 15, 'add_releaseversionlog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (44, 'Can change 版本日志', 15, 'change_releaseversionlog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (45, 'Can delete 版本日志', 15, 'delete_releaseversionlog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (46, 'Can add Pipeline实例', 16, 'add_pipelineinstance');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (47, 'Can change Pipeline实例', 16, 'change_pipelineinstance');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (48, 'Can delete Pipeline实例', 16, 'delete_pipelineinstance');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (49, 'Can add Pipeline模板', 17, 'add_pipelinetemplate');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (50, 'Can change Pipeline模板', 17, 'change_pipelinetemplate');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (51, 'Can delete Pipeline模板', 17, 'delete_pipelinetemplate');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (52, 'Can add 模板快照', 18, 'add_snapshot');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (53, 'Can change 模板快照', 18, 'change_snapshot');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (54, 'Can delete 模板快照', 18, 'delete_snapshot');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (55, 'Can add template scheme', 19, 'add_templatescheme');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (56, 'Can change template scheme', 19, 'change_templatescheme');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (57, 'Can delete template scheme', 19, 'delete_templatescheme');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (58, 'Can add tree info', 20, 'add_treeinfo');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (59, 'Can change tree info', 20, 'change_treeinfo');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (60, 'Can delete tree info', 20, 'delete_treeinfo');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (61, 'Can add template version', 21, 'add_templateversion');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (62, 'Can change template version', 21, 'change_templateversion');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (63, 'Can delete template version', 21, 'delete_templateversion');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (64, 'Can add template relationship', 22, 'add_templaterelationship');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (65, 'Can change template relationship', 22, 'change_templaterelationship');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (66, 'Can delete template relationship', 22, 'delete_templaterelationship');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (67, 'Can add template current version', 23, 'add_templatecurrentversion');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (68, 'Can change template current version', 23, 'change_templatecurrentversion');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (69, 'Can delete template current version', 23, 'delete_templatecurrentversion');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (70, 'Can add signal', 24, 'add_signal');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (71, 'Can change signal', 24, 'change_signal');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (72, 'Can delete signal', 24, 'delete_signal');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (73, 'Can add log entry', 25, 'add_logentry');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (74, 'Can change log entry', 25, 'change_logentry');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (75, 'Can delete log entry', 25, 'delete_logentry');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (76, 'Can add data', 26, 'add_data');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (77, 'Can change data', 26, 'change_data');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (78, 'Can delete data', 26, 'delete_data');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (79, 'Can add history', 27, 'add_history');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (80, 'Can change history', 27, 'change_history');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (81, 'Can delete history', 27, 'delete_history');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (82, 'Can add history data', 28, 'add_historydata');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (83, 'Can change history data', 28, 'change_historydata');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (84, 'Can delete history data', 28, 'delete_historydata');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (85, 'Can add node relationship', 29, 'add_noderelationship');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (86, 'Can change node relationship', 29, 'change_noderelationship');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (87, 'Can delete node relationship', 29, 'delete_noderelationship');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (88, 'Can add pipeline model', 30, 'add_pipelinemodel');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (89, 'Can change pipeline model', 30, 'change_pipelinemodel');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (90, 'Can delete pipeline model', 30, 'delete_pipelinemodel');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (91, 'Can add pipeline process', 31, 'add_pipelineprocess');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (92, 'Can change pipeline process', 31, 'change_pipelineprocess');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (93, 'Can delete pipeline process', 31, 'delete_pipelineprocess');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (94, 'Can add process celery task', 32, 'add_processcelerytask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (95, 'Can change process celery task', 32, 'change_processcelerytask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (96, 'Can delete process celery task', 32, 'delete_processcelerytask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (97, 'Can add process snapshot', 33, 'add_processsnapshot');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (98, 'Can change process snapshot', 33, 'change_processsnapshot');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (99, 'Can delete process snapshot', 33, 'delete_processsnapshot');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (100, 'Can add schedule service', 34, 'add_scheduleservice');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (101, 'Can change schedule service', 34, 'change_scheduleservice');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (102, 'Can delete schedule service', 34, 'delete_scheduleservice');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (103, 'Can add status', 35, 'add_status');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (104, 'Can change status', 35, 'change_status');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (105, 'Can delete status', 35, 'delete_status');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (106, 'Can add sub process relationship', 36, 'add_subprocessrelationship');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (107, 'Can change sub process relationship', 36, 'change_subprocessrelationship');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (108, 'Can delete sub process relationship', 36, 'delete_subprocessrelationship');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (109, 'Can add function switch', 37, 'add_functionswitch');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (110, 'Can change function switch', 37, 'change_functionswitch');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (111, 'Can delete function switch', 37, 'delete_functionswitch');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (112, 'Can add schedule celery task', 38, 'add_schedulecelerytask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (113, 'Can change schedule celery task', 38, 'change_schedulecelerytask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (114, 'Can delete schedule celery task', 38, 'delete_schedulecelerytask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (115, 'Can add node celery task', 39, 'add_nodecelerytask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (116, 'Can change node celery task', 39, 'change_nodecelerytask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (117, 'Can delete node celery task', 39, 'delete_nodecelerytask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (118, 'Can add data snapshot', 40, 'add_datasnapshot');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (119, 'Can change data snapshot', 40, 'change_datasnapshot');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (120, 'Can delete data snapshot', 40, 'delete_datasnapshot');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (121, 'Can add multi callback data', 41, 'add_multicallbackdata');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (122, 'Can change multi callback data', 41, 'change_multicallbackdata');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (123, 'Can delete multi callback data', 41, 'delete_multicallbackdata');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (124, 'Can add send failed celery task', 42, 'add_sendfailedcelerytask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (125, 'Can change send failed celery task', 42, 'change_sendfailedcelerytask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (126, 'Can delete send failed celery task', 42, 'delete_sendfailedcelerytask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (127, 'Can add 组件 Component', 43, 'add_componentmodel');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (128, 'Can change 组件 Component', 43, 'change_componentmodel');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (129, 'Can delete 组件 Component', 43, 'delete_componentmodel');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (130, 'Can add Variable变量', 44, 'add_variablemodel');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (131, 'Can change Variable变量', 44, 'change_variablemodel');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (132, 'Can delete Variable变量', 44, 'delete_variablemodel');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (133, 'Can add crontab', 45, 'add_crontabschedule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (134, 'Can change crontab', 45, 'change_crontabschedule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (135, 'Can delete crontab', 45, 'delete_crontabschedule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (136, 'Can add djcelery periodic task', 46, 'add_djceleryperiodictask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (137, 'Can change djcelery periodic task', 46, 'change_djceleryperiodictask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (138, 'Can delete djcelery periodic task', 46, 'delete_djceleryperiodictask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (139, 'Can add dj celery periodic tasks', 47, 'add_djceleryperiodictasks');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (140, 'Can change dj celery periodic tasks', 47, 'change_djceleryperiodictasks');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (141, 'Can delete dj celery periodic tasks', 47, 'delete_djceleryperiodictasks');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (142, 'Can add interval', 48, 'add_intervalschedule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (143, 'Can change interval', 48, 'change_intervalschedule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (144, 'Can delete interval', 48, 'delete_intervalschedule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (145, 'Can add periodic task', 49, 'add_periodictask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (146, 'Can change periodic task', 49, 'change_periodictask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (147, 'Can delete periodic task', 49, 'delete_periodictask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (148, 'Can add periodic task history', 50, 'add_periodictaskhistory');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (149, 'Can change periodic task history', 50, 'change_periodictaskhistory');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (150, 'Can delete periodic task history', 50, 'delete_periodictaskhistory');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (151, 'Can add signal', 51, 'add_signal');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (152, 'Can change signal', 51, 'change_signal');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (153, 'Can delete signal', 51, 'delete_signal');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (154, 'Can add 用户角色类型', 52, 'add_roletype');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (155, 'Can change 用户角色类型', 52, 'change_roletype');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (156, 'Can delete 用户角色类型', 52, 'delete_roletype');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (157, 'Can add 用户角色和权限表', 53, 'add_userrole');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (158, 'Can change 用户角色和权限表', 53, 'change_userrole');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (159, 'Can delete 用户角色和权限表', 53, 'delete_userrole');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (160, 'Can add 蓝鲸用户角色表', 54, 'add_bkuserrole');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (161, 'Can change 蓝鲸用户角色表', 54, 'change_bkuserrole');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (162, 'Can delete 蓝鲸用户角色表', 54, 'delete_bkuserrole');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (163, 'Can add 工单', 55, 'add_ticket');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (164, 'Can change 工单', 55, 'change_ticket');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (165, 'Can delete 工单', 55, 'delete_ticket');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (166, 'Can add 单据流转日志', 56, 'add_ticketeventlog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (167, 'Can change 单据流转日志', 56, 'change_ticketeventlog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (168, 'Can delete 单据流转日志', 56, 'delete_ticketeventlog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (169, 'Can add 表单字段值', 57, 'add_ticketfield');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (170, 'Can change 表单字段值', 57, 'change_ticketfield');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (171, 'Can delete 表单字段值', 57, 'delete_ticketfield');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (172, 'Can add 单据模板', 58, 'add_tickettemplate');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (173, 'Can change 单据模板', 58, 'change_tickettemplate');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (174, 'Can delete 单据模板', 58, 'delete_tickettemplate');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (175, 'Can add 工单评价', 59, 'add_ticketcomment');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (176, 'Can change 工单评价', 59, 'change_ticketcomment');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (177, 'Can delete 工单评价', 59, 'delete_ticketcomment');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (178, 'Can add 邀请途径记录', 60, 'add_ticketcommentinvite');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (179, 'Can change 邀请途径记录', 60, 'change_ticketcommentinvite');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (180, 'Can delete 邀请途径记录', 60, 'delete_ticketcommentinvite');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (181, 'Can add 单据节点草稿', 61, 'add_ticketstatedraft');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (182, 'Can change 单据节点草稿', 61, 'change_ticketstatedraft');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (183, 'Can delete 单据节点草稿', 61, 'delete_ticketstatedraft');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (184, 'Can add 关注人通知日志', 62, 'add_ticketfollowernotifylog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (185, 'Can change 关注人通知日志', 62, 'change_ticketfollowernotifylog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (186, 'Can delete 关注人通知日志', 62, 'delete_ticketfollowernotifylog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (187, 'Can add 督办日志', 63, 'add_ticketsupervisenotifylog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (188, 'Can change 督办日志', 63, 'change_ticketsupervisenotifylog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (189, 'Can delete 督办日志', 63, 'delete_ticketsupervisenotifylog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (190, 'Can add 节点处理状态', 64, 'add_status');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (191, 'Can change 节点处理状态', 64, 'change_status');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (192, 'Can delete 节点处理状态', 64, 'delete_status');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (193, 'Can add 单据全局变量', 65, 'add_ticketglobalvariable');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (194, 'Can change 单据全局变量', 65, 'change_ticketglobalvariable');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (195, 'Can delete 单据全局变量', 65, 'delete_ticketglobalvariable');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (196, 'Can add 单据间关联', 66, 'add_tickettoticket');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (197, 'Can change 单据间关联', 66, 'change_tickettoticket');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (198, 'Can delete 单据间关联', 66, 'delete_tickettoticket');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (199, 'Can add 单据状态流转日志', 67, 'add_statustransitlog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (200, 'Can change 单据状态流转日志', 67, 'change_statustransitlog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (201, 'Can delete 单据状态流转日志', 67, 'delete_statustransitlog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (202, 'Can add 会签任务', 68, 'add_signtask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (203, 'Can change 会签任务', 68, 'change_signtask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (204, 'Can delete 会签任务', 68, 'delete_signtask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (205, 'Can add 任务字段值', 69, 'add_taskfield');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (206, 'Can change 任务字段值', 69, 'change_taskfield');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (207, 'Can delete 任务字段值', 69, 'delete_taskfield');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (208, 'Can add 单据关注人', 70, 'add_attentionusers');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (209, 'Can change 单据关注人', 70, 'change_attentionusers');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (210, 'Can delete 单据关注人', 70, 'delete_attentionusers');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (211, 'Can add 用户组织', 71, 'add_ticketorganization');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (212, 'Can change 用户组织', 71, 'change_ticketorganization');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (213, 'Can delete 用户组织', 71, 'delete_ticketorganization');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (214, 'Can add 服务属性记录', 72, 'add_propertyrecord');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (215, 'Can change 服务属性记录', 72, 'change_propertyrecord');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (216, 'Can delete 服务属性记录', 72, 'delete_propertyrecord');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (217, 'Can add 服务类型', 73, 'add_servicecategory');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (218, 'Can change 服务类型', 73, 'change_servicecategory');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (219, 'Can delete 服务类型', 73, 'delete_servicecategory');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (220, 'Can add 服务属性', 74, 'add_serviceproperty');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (221, 'Can change 服务属性', 74, 'change_serviceproperty');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (222, 'Can delete 服务属性', 74, 'delete_serviceproperty');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (223, 'Can add 用户收藏', 75, 'add_favorite');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (224, 'Can change 用户收藏', 75, 'change_favorite');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (225, 'Can delete 用户收藏', 75, 'delete_favorite');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (226, 'Can add 服务分类表', 76, 'add_catalogservice');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (227, 'Can change 服务分类表', 76, 'change_catalogservice');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (228, 'Can delete 服务分类表', 76, 'delete_catalogservice');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (229, 'Can add 字典数据', 77, 'add_dictdata');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (230, 'Can change 字典数据', 77, 'change_dictdata');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (231, 'Can delete 字典数据', 77, 'delete_dictdata');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (232, 'Can add 服务', 78, 'add_service');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (233, 'Can change 服务', 78, 'change_service');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (234, 'Can delete 服务', 78, 'delete_service');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (235, 'Can add 服务目录', 79, 'add_servicecatalog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (236, 'Can change 服务目录', 79, 'change_servicecatalog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (237, 'Can delete 服务目录', 79, 'delete_servicecatalog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (238, 'Can add 数据字典', 80, 'add_sysdict');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (239, 'Can change 数据字典', 80, 'change_sysdict');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (240, 'Can delete 数据字典', 80, 'delete_sysdict');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (241, 'Can add 服务级别', 81, 'add_oldsla');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (242, 'Can change 服务级别', 81, 'change_oldsla');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (243, 'Can delete 服务级别', 81, 'delete_oldsla');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (244, 'Can add 用户收藏', 82, 'add_favoriteservice');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (245, 'Can change 用户收藏', 82, 'change_favoriteservice');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (246, 'Can delete 用户收藏', 82, 'delete_favoriteservice');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (247, 'Can add 内置字段表', 83, 'add_defaultfield');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (248, 'Can change 内置字段表', 83, 'change_defaultfield');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (249, 'Can delete 内置字段表', 83, 'delete_defaultfield');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (250, 'Can add 字段表', 84, 'add_field');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (251, 'Can change 字段表', 84, 'change_field');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (252, 'Can delete 字段表', 84, 'delete_field');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (253, 'Can add 通知方式', 85, 'add_notify');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (254, 'Can change 通知方式', 85, 'change_notify');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (255, 'Can delete 通知方式', 85, 'delete_notify');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (256, 'Can add 状态', 86, 'add_state');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (257, 'Can change 状态', 86, 'change_state');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (258, 'Can delete 状态', 86, 'delete_state');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (259, 'Can add 状态流转', 87, 'add_transition');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (260, 'Can change 状态流转', 87, 'change_transition');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (261, 'Can delete 状态流转', 87, 'delete_transition');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (262, 'Can add 流程模板', 88, 'add_workflow');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (263, 'Can change 流程模板', 88, 'change_workflow');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (264, 'Can delete 流程模板', 88, 'delete_workflow');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (265, 'Can add 工作流快照', 89, 'add_workflowsnap');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (266, 'Can change 工作流快照', 89, 'change_workflowsnap');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (267, 'Can delete 工作流快照', 89, 'delete_workflowsnap');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (268, 'Can add 流程快照', 90, 'add_workflowversion');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (269, 'Can change 流程快照', 90, 'change_workflowversion');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (270, 'Can delete 流程快照', 90, 'delete_workflowversion');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (271, 'Can add 流转条件', 91, 'add_condition');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (272, 'Can change 流转条件', 91, 'change_condition');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (273, 'Can delete 流转条件', 91, 'delete_condition');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (274, 'Can add 全局变量', 92, 'add_globalvariable');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (275, 'Can change 全局变量', 92, 'change_globalvariable');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (276, 'Can delete 全局变量', 92, 'delete_globalvariable');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (277, 'Can add 基础模型', 93, 'add_table');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (278, 'Can change 基础模型', 93, 'change_table');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (279, 'Can delete 基础模型', 93, 'delete_table');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (280, 'Can add 字段库', 94, 'add_templatefield');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (281, 'Can change 字段库', 94, 'change_templatefield');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (282, 'Can delete 字段库', 94, 'delete_templatefield');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (283, 'Can add 触发器', 95, 'add_trigger');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (284, 'Can change 触发器', 95, 'change_trigger');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (285, 'Can delete 触发器', 95, 'delete_trigger');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (286, 'Can add 任务字段表', 96, 'add_taskfieldschema');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (287, 'Can change 任务字段表', 96, 'change_taskfieldschema');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (288, 'Can delete 任务字段表', 96, 'delete_taskfieldschema');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (289, 'Can add 任务模型', 97, 'add_taskschema');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (290, 'Can change 任务模型', 97, 'change_taskschema');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (291, 'Can delete 任务模型', 97, 'delete_taskschema');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (292, 'Can add 升级事件配置', 98, 'add_action');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (293, 'Can change 升级事件配置', 98, 'change_action');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (294, 'Can delete 升级事件配置', 98, 'delete_action');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (295, 'Can add 升级策略', 99, 'add_actionpolicy');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (296, 'Can change 升级策略', 99, 'change_actionpolicy');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (297, 'Can delete 升级策略', 99, 'delete_actionpolicy');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (298, 'Can add 工作日和节假日', 100, 'add_day');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (299, 'Can change 工作日和节假日', 100, 'change_day');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (300, 'Can delete 工作日和节假日', 100, 'delete_day');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (301, 'Can add 工作时间段', 101, 'add_duration');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (302, 'Can change 工作时间段', 101, 'change_duration');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (303, 'Can delete 工作时间段', 101, 'delete_duration');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (304, 'Can add 优先级矩阵', 102, 'add_prioritymatrix');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (305, 'Can change 优先级矩阵', 102, 'change_prioritymatrix');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (306, 'Can delete 优先级矩阵', 102, 'delete_prioritymatrix');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (307, 'Can add 服务策略', 103, 'add_prioritypolicy');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (308, 'Can change 服务策略', 103, 'change_prioritypolicy');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (309, 'Can delete 服务策略', 103, 'delete_prioritypolicy');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (310, 'Can add 服务运营时间', 104, 'add_schedule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (311, 'Can change 服务运营时间', 104, 'change_schedule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (312, 'Can delete 服务运营时间', 104, 'delete_schedule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (313, 'Can add 服务协议', 105, 'add_sla');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (314, 'Can change 服务协议', 105, 'change_sla');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (315, 'Can delete 服务协议', 105, 'delete_sla');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (316, 'Can add 计时规则', 106, 'add_slatimerrule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (317, 'Can change 计时规则', 106, 'change_slatimerrule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (318, 'Can delete 计时规则', 106, 'delete_slatimerrule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (319, 'Can add 状态转换规则', 107, 'add_statustransit');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (320, 'Can change 状态转换规则', 107, 'change_statustransit');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (321, 'Can delete 状态转换规则', 107, 'delete_statustransit');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (322, 'Can add 工单状态', 108, 'add_ticketstatus');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (323, 'Can change 工单状态', 108, 'change_ticketstatus');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (324, 'Can delete 工单状态', 108, 'delete_ticketstatus');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (325, 'Can add 工单状态配置', 109, 'add_ticketstatusconfig');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (326, 'Can change 工单状态配置', 109, 'change_ticketstatusconfig');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (327, 'Can delete 工单状态配置', 109, 'delete_ticketstatusconfig');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (328, 'Can add sla行为历史记录', 110, 'add_slaactionhistory');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (329, 'Can change sla行为历史记录', 110, 'change_slaactionhistory');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (330, 'Can delete sla行为历史记录', 110, 'delete_slaactionhistory');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (331, 'Can add sla事件日志', 111, 'add_slaeventlog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (332, 'Can change sla事件日志', 111, 'change_slaeventlog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (333, 'Can delete sla事件日志', 111, 'delete_slaeventlog');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (334, 'Can add sla任务', 112, 'add_slatask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (335, 'Can change sla任务', 112, 'change_slatask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (336, 'Can delete sla任务', 112, 'delete_slatask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (337, 'Can add 第三方API配置', 113, 'add_remoteapi');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (338, 'Can change 第三方API配置', 113, 'change_remoteapi');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (339, 'Can delete 第三方API配置', 113, 'delete_remoteapi');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (340, 'Can add API配置参数实例', 114, 'add_remoteapiinstance');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (341, 'Can change API配置参数实例', 114, 'change_remoteapiinstance');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (342, 'Can delete API配置参数实例', 114, 'delete_remoteapiinstance');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (343, 'Can add 第三方系统配置', 115, 'add_remotesystem');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (344, 'Can change 第三方系统配置', 115, 'change_remotesystem');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (345, 'Can delete 第三方系统配置', 115, 'delete_remotesystem');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (346, 'Can add 响应动作表', 116, 'add_action');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (347, 'Can change 响应动作表', 116, 'change_action');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (348, 'Can delete 响应动作表', 116, 'delete_action');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (349, 'Can add 响应动作参数配置表', 117, 'add_actionschema');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (350, 'Can change 响应动作参数配置表', 117, 'change_actionschema');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (351, 'Can delete 响应动作参数配置表', 117, 'delete_actionschema');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (352, 'Can add 触发器', 118, 'add_trigger');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (353, 'Can change 触发器', 118, 'change_trigger');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (354, 'Can delete 触发器', 118, 'delete_trigger');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (355, 'Can add 触发器条件与动作配置', 119, 'add_triggerrule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (356, 'Can change 触发器条件与动作配置', 119, 'change_triggerrule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (357, 'Can delete 触发器条件与动作配置', 119, 'delete_triggerrule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (358, 'Can add 子任务', 120, 'add_task');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (359, 'Can change 子任务', 120, 'change_task');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (360, 'Can delete 子任务', 120, 'delete_task');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (361, 'Can add 任务字段表', 121, 'add_taskfield');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (362, 'Can change 任务字段表', 121, 'change_taskfield');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (363, 'Can delete 任务字段表', 121, 'delete_taskfield');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (364, 'Can add 标准运维任务', 122, 'add_sopstask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (365, 'Can change 标准运维任务', 122, 'change_sopstask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (366, 'Can delete 标准运维任务', 122, 'delete_sopstask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (367, 'Can add 任务库', 123, 'add_tasklib');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (368, 'Can change 任务库', 123, 'change_tasklib');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (369, 'Can delete 任务库', 123, 'delete_tasklib');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (370, 'Can add record', 124, 'add_record');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (371, 'Can change record', 124, 'change_record');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (372, 'Can delete record', 124, 'delete_record');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (373, 'Can add type', 125, 'add_notificationtype');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (374, 'Can change type', 125, 'change_notificationtype');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (375, 'Can delete type', 125, 'delete_notificationtype');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (376, 'Can add settings', 126, 'add_settings');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (377, 'Can change settings', 126, 'change_settings');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (378, 'Can delete settings', 126, 'delete_settings');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (379, 'Can add notification', 127, 'add_notification');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (380, 'Can change notification', 127, 'change_notification');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (381, 'Can delete notification', 127, 'delete_notification');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (382, 'Can add subscription', 128, 'add_subscription');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (383, 'Can change subscription', 128, 'change_subscription');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (384, 'Can delete subscription', 128, 'delete_subscription');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (385, 'Can add kv store', 129, 'add_kvstore');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (386, 'Can change kv store', 129, 'change_kvstore');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (387, 'Can delete kv store', 129, 'delete_kvstore');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (388, 'Can add article', 130, 'add_article');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (389, 'Can change article', 130, 'change_article');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (390, 'Can delete article', 130, 'delete_article');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (391, 'Can edit all articles and lock/unlock/restore', 130, 'moderate');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (392, 'Can change ownership of any article', 130, 'assign');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (393, 'Can assign permissions to other users', 130, 'grant');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (394, 'Can add Article for object', 131, 'add_articleforobject');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (395, 'Can change Article for object', 131, 'change_articleforobject');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (396, 'Can delete Article for object', 131, 'delete_articleforobject');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (397, 'Can add article plugin', 132, 'add_articleplugin');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (398, 'Can change article plugin', 132, 'change_articleplugin');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (399, 'Can delete article plugin', 132, 'delete_articleplugin');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (400, 'Can add article revision', 133, 'add_articlerevision');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (401, 'Can change article revision', 133, 'change_articlerevision');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (402, 'Can delete article revision', 133, 'delete_articlerevision');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (403, 'Can add reusable plugin', 134, 'add_reusableplugin');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (404, 'Can change reusable plugin', 134, 'change_reusableplugin');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (405, 'Can delete reusable plugin', 134, 'delete_reusableplugin');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (406, 'Can add revision plugin', 135, 'add_revisionplugin');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (407, 'Can change revision plugin', 135, 'change_revisionplugin');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (408, 'Can delete revision plugin', 135, 'delete_revisionplugin');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (409, 'Can add revision plugin revision', 136, 'add_revisionpluginrevision');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (410, 'Can change revision plugin revision', 136, 'change_revisionpluginrevision');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (411, 'Can delete revision plugin revision', 136, 'delete_revisionpluginrevision');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (412, 'Can add simple plugin', 137, 'add_simpleplugin');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (413, 'Can change simple plugin', 137, 'change_simpleplugin');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (414, 'Can delete simple plugin', 137, 'delete_simpleplugin');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (415, 'Can add URL path', 138, 'add_urlpath');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (416, 'Can change URL path', 138, 'change_urlpath');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (417, 'Can delete URL path', 138, 'delete_urlpath');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (418, 'Can add attachment', 139, 'add_attachment');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (419, 'Can change attachment', 139, 'change_attachment');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (420, 'Can delete attachment', 139, 'delete_attachment');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (421, 'Can add attachment revision', 140, 'add_attachmentrevision');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (422, 'Can change attachment revision', 140, 'change_attachmentrevision');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (423, 'Can delete attachment revision', 140, 'delete_attachmentrevision');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (424, 'Can add image', 141, 'add_image');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (425, 'Can change image', 141, 'change_image');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (426, 'Can delete image', 141, 'delete_image');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (427, 'Can add image revision', 142, 'add_imagerevision');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (428, 'Can change image revision', 142, 'change_imagerevision');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (429, 'Can delete image revision', 142, 'delete_imagerevision');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (430, 'Can add 微信用户', 143, 'add_bkweixinuser');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (431, 'Can change 微信用户', 143, 'change_bkweixinuser');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (432, 'Can delete 微信用户', 143, 'delete_bkweixinuser');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (433, 'Can add crontab', 144, 'add_crontabschedule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (434, 'Can change crontab', 144, 'change_crontabschedule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (435, 'Can delete crontab', 144, 'delete_crontabschedule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (436, 'Can add interval', 145, 'add_intervalschedule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (437, 'Can change interval', 145, 'change_intervalschedule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (438, 'Can delete interval', 145, 'delete_intervalschedule');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (439, 'Can add periodic task', 146, 'add_periodictask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (440, 'Can change periodic task', 146, 'change_periodictask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (441, 'Can delete periodic task', 146, 'delete_periodictask');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (442, 'Can add periodic tasks', 147, 'add_periodictasks');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (443, 'Can change periodic tasks', 147, 'change_periodictasks');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (444, 'Can delete periodic tasks', 147, 'delete_periodictasks');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (445, 'Can add task state', 148, 'add_taskmeta');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (446, 'Can change task state', 148, 'change_taskmeta');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (447, 'Can delete task state', 148, 'delete_taskmeta');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (448, 'Can add saved group result', 149, 'add_tasksetmeta');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (449, 'Can change saved group result', 149, 'change_tasksetmeta');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (450, 'Can delete saved group result', 149, 'delete_tasksetmeta');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (451, 'Can add task', 150, 'add_taskstate');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (452, 'Can change task', 150, 'change_taskstate');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (453, 'Can delete task', 150, 'delete_taskstate');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (454, 'Can add worker', 151, 'add_workerstate');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (455, 'Can change worker', 151, 'change_workerstate');
INSERT INTO bk_itsm.auth_permission (id, name, content_type_id, codename) VALUES (456, 'Can delete worker', 151, 'delete_workerstate');
