create table ticket_ticketfield
(
    id                int auto_increment
        primary key,
    creator           varchar(64)    null,
    create_at         datetime(6)    not null,
    update_at         datetime(6)    not null,
    updated_by        varchar(64)    null,
    end_at            datetime(6)    null,
    is_deleted        tinyint(1)     not null,
    is_builtin        tinyint(1)     not null,
    is_readonly       tinyint(1)     not null,
    is_valid          tinyint(1)     not null,
    display           tinyint(1)     not null,
    source_type       varchar(32)    not null,
    source_uri        varchar(255)   null,
    type              varchar(32)    not null,
    `key`             varchar(255)   not null,
    name              varchar(64)    not null,
    layout            varchar(32)    not null,
    validate_type     varchar(32)    not null,
    regex             varchar(64)    null,
    `desc`            varchar(128)   null,
    `default`         varchar(10000) null,
    choice            longtext       not null,
    related_fields    longtext       null,
    state_id          varchar(32)    null,
    _value            longtext       null,
    ticket_id         int            not null,
    custom_regex      varchar(128)   null,
    meta              longtext       not null,
    api_instance_id   int            null,
    is_tips           tinyint(1)     not null,
    kv_relation       varchar(64)    not null,
    show_conditions   longtext       not null,
    show_type         int            not null,
    tips              varchar(128)   null,
    source            varchar(32)    not null,
    workflow_field_id int            not null,
    regex_config      varchar(255)   not null,
    constraint ticket_ticketfield_ticket_id_0e39dba7_fk_ticket_ticket_id
        foreign key (ticket_id) references ticket_ticket (id)
);

create index ticket_ticketfield_is_deleted_70491694
    on ticket_ticketfield (is_deleted);

INSERT INTO bk_itsm.ticket_ticketfield (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, _value, ticket_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, workflow_field_id, regex_config) VALUES (1, null, '2022-04-04 19:51:16.263627', '2022-04-04 19:51:16.308301', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 'STRING', 'title', '标题', 'COL_12', 'REQUIRE', 'EMPTY', '请输入标题', '', '[]', '{}', '', 'kk', 1, '', '{}', 0, 0, '{}', '{}', 1, '', 'BASE-MODEL', 1, '{}');
INSERT INTO bk_itsm.ticket_ticketfield (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, _value, ticket_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, workflow_field_id, regex_config) VALUES (2, null, '2022-04-04 19:51:16.263789', '2022-04-04 19:51:16.263797', null, null, 0, 1, 0, 1, 1, 'RPC', 'ticket_status', 'SELECT', 'current_status', '工单状态', 'COL_12', 'REQUIRE', 'EMPTY', '请选择工单状态', '', '[{"name":"\\u5df2\\u5b8c\\u6210","key":"FINISHED","is_over":"True"},{"name":"\\u5df2\\u7ec8\\u6b62","key":"TERMINATED","is_over":"True"},{"name":"\\u5df2\\u64a4\\u9500","key":"REVOKED","is_over":"True"}]', '{}', '', 'FINISHED', 1, '', '{}', 0, 0, '{}', '{}', 1, '', 'BASE-MODEL', 5, '{}');
INSERT INTO bk_itsm.ticket_ticketfield (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, _value, ticket_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, workflow_field_id, regex_config) VALUES (3, null, '2022-04-04 19:51:16.263892', '2022-04-04 19:51:16.311472', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 'TEXT', 'apply_content', '申请内容', 'COL_12', 'REQUIRE', 'EMPTY', '请输入申请内容', '', '[]', '{}', '', 'dsd', 1, '', '{}', 0, 0, '{}', '{}', 1, '', 'BASE-MODEL', 6, '{}');
INSERT INTO bk_itsm.ticket_ticketfield (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, _value, ticket_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, workflow_field_id, regex_config) VALUES (4, null, '2022-04-04 19:51:16.263980', '2022-04-04 19:51:16.314435', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 'TEXT', 'apply_reason', '申请理由', 'COL_12', 'REQUIRE', 'EMPTY', '请输入理由', '', '[]', '{}', '', 'sd', 1, '', '{}', 0, 0, '{}', '{}', 1, '', 'BASE-MODEL', 7, '{}');
INSERT INTO bk_itsm.ticket_ticketfield (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, _value, ticket_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, workflow_field_id, regex_config) VALUES (5, null, '2022-04-04 19:51:16.264067', '2022-04-04 19:51:16.309188', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 'STRING', 'title', '标题', 'COL_12', 'REQUIRE', 'EMPTY', '请输入标题', '', '[]', '{}', '', 'kk', 1, '', '{}', 0, 0, '{}', '{}', 1, '', 'TABLE', 1, '{}');
INSERT INTO bk_itsm.ticket_ticketfield (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, _value, ticket_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, workflow_field_id, regex_config) VALUES (6, null, '2022-04-04 19:51:16.264165', '2022-04-04 19:51:16.312200', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', 'apply_content', '申请内容', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', '2', 'dsd', 1, '', '{}', 0, 0, '{}', '{}', 1, '', 'TABLE', 2, '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.ticket_ticketfield (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, _value, ticket_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, workflow_field_id, regex_config) VALUES (7, null, '2022-04-04 19:51:16.264259', '2022-04-04 19:51:16.315165', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', 'apply_reason', '申请理由', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', '2', 'sd', 1, '', '{}', 0, 0, '{}', '{}', 1, '', 'TABLE', 3, '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.ticket_ticketfield (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, _value, ticket_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, workflow_field_id, regex_config) VALUES (8, null, '2022-04-04 19:51:16.264351', '2022-04-04 19:51:16.318065', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'MEMBERS', 'ZHIDINGSHENPIREN', '指定审批人', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', '2', 'admin', 1, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', 4, '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.ticket_ticketfield (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, _value, ticket_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, workflow_field_id, regex_config) VALUES (9, null, '2022-04-04 19:51:16.264441', '2022-04-04 19:51:16.264447', null, null, 0, 0, 0, 1, 1, 'CUSTOM', '', 'RADIO', '27924a83a1b9d239086e9724264a53e3', '审批意见', 'COL_6', 'REQUIRE', 'EMPTY', '', '', '[{"key":"true","name":"\\u901a\\u8fc7"},{"key":"false","name":"\\u62d2\\u7edd"}]', '{}', '4', 'true', 1, '', '{"code":"APPROVE_RESULT"}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', 5, '{}');
INSERT INTO bk_itsm.ticket_ticketfield (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, _value, ticket_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, workflow_field_id, regex_config) VALUES (10, null, '2022-04-04 19:51:16.264533', '2022-04-04 19:51:16.264539', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', '63f03ddeb567ba12dd711db71ee46e66', '备注', 'COL_12', 'OPTION', 'EMPTY', '', '', '[]', '{}', '4', null, 1, '', '{}', 0, 0, '{}', '{"expressions":[{"value":"false","type":"RADIO","condition":"==","key":"27924a83a1b9d239086e9724264a53e3"}],"type":"and"}', 0, '', 'CUSTOM', 6, '{}');
INSERT INTO bk_itsm.ticket_ticketfield (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, _value, ticket_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, workflow_field_id, regex_config) VALUES (11, null, '2022-04-04 19:51:16.264625', '2022-04-04 19:51:16.264631', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', '71f9445928b83fd2aec3c2e0deea4889', '备注', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', '4', null, 1, '', '{}', 0, 0, '{}', '{"expressions":[{"value":"true","type":"RADIO","condition":"==","key":"27924a83a1b9d239086e9724264a53e3"}],"type":"and"}', 0, '', 'CUSTOM', 7, '{}');
INSERT INTO bk_itsm.ticket_ticketfield (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, _value, ticket_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, workflow_field_id, regex_config) VALUES (12, null, '2022-04-04 19:51:16.264716', '2022-04-04 19:51:16.264722', null, null, 0, 0, 0, 1, 1, 'CUSTOM', '', 'RADIO', 'a00592c80f7febec616849b177a6cf5d', '审批意见', 'COL_6', 'REQUIRE', 'EMPTY', '', '', '[{"key":"true","name":"\\u901a\\u8fc7"},{"key":"false","name":"\\u62d2\\u7edd"}]', '{}', '5', 'true', 1, '', '{"code":"APPROVE_RESULT"}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', 8, '{}');
INSERT INTO bk_itsm.ticket_ticketfield (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, _value, ticket_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, workflow_field_id, regex_config) VALUES (13, null, '2022-04-04 19:51:16.264807', '2022-04-04 19:51:16.264814', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', '94c49c3a5047dda38ed1e07fb53c025d', '备注', 'COL_12', 'OPTION', 'EMPTY', '', '', '[]', '{}', '5', null, 1, '', '{}', 0, 0, '{}', '{"expressions":[{"value":"false","type":"RADIO","condition":"==","key":"a00592c80f7febec616849b177a6cf5d"}],"type":"and"}', 0, '', 'CUSTOM', 9, '{}');
INSERT INTO bk_itsm.ticket_ticketfield (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, _value, ticket_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, workflow_field_id, regex_config) VALUES (14, null, '2022-04-04 19:51:16.264899', '2022-04-04 19:51:16.264905', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', '3d1fbe249001dd755c075418904be892', '备注', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', '5', null, 1, '', '{}', 0, 0, '{}', '{"expressions":[{"value":"true","type":"RADIO","condition":"==","key":"a00592c80f7febec616849b177a6cf5d"}],"type":"and"}', 0, '', 'CUSTOM', 10, '{}');
