create table workflow_field
(
    id              int auto_increment
        primary key,
    creator         varchar(64)    null,
    create_at       datetime(6)    not null,
    update_at       datetime(6)    not null,
    updated_by      varchar(64)    null,
    end_at          datetime(6)    null,
    is_deleted      tinyint(1)     not null,
    is_builtin      tinyint(1)     not null,
    is_readonly     tinyint(1)     not null,
    is_valid        tinyint(1)     not null,
    display         tinyint(1)     not null,
    source_type     varchar(32)    not null,
    source_uri      varchar(255)   null,
    type            varchar(32)    not null,
    `key`           varchar(255)   not null,
    name            varchar(64)    not null,
    layout          varchar(32)    not null,
    validate_type   varchar(32)    not null,
    regex           varchar(64)    null,
    `desc`          varchar(128)   null,
    `default`       varchar(10000) null,
    choice          longtext       not null,
    related_fields  longtext       null,
    state_id        int            null,
    workflow_id     int            not null,
    custom_regex    varchar(128)   null,
    meta            longtext       not null,
    api_instance_id int            null,
    is_tips         tinyint(1)     not null,
    kv_relation     varchar(64)    not null,
    show_conditions longtext       not null,
    show_type       int            not null,
    tips            varchar(128)   null,
    source          varchar(32)    not null,
    regex_config    varchar(255)   not null,
    constraint workflow_field_state_id_cbd85589_fk_workflow_state_id
        foreign key (state_id) references workflow_state (id),
    constraint workflow_field_workflow_id_6658e57a_fk_workflow_workflow_id
        foreign key (workflow_id) references workflow_workflow (id)
);

create index workflow_field_is_deleted_821260ac
    on workflow_field (is_deleted);

INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (1, null, '2022-04-04 18:29:34.413629', '2022-04-04 18:29:34.413640', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 'STRING', 'title', '标题', 'COL_12', 'REQUIRE', 'EMPTY', '请输入标题', '', '[]', '{}', null, 1, '', '{}', 0, 0, '{}', '{}', 1, '', 'TABLE', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (2, null, '2022-04-04 18:29:34.414214', '2022-04-04 18:29:34.414228', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', 'apply_content', '申请内容', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 2, 1, '', '{}', 0, 0, '{}', '{}', 1, '', 'TABLE', '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (3, null, '2022-04-04 18:29:34.414874', '2022-04-04 18:29:34.414885', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', 'apply_reason', '申请理由', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 2, 1, '', '{}', 0, 0, '{}', '{}', 1, '', 'TABLE', '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (4, null, '2022-04-04 18:29:34.415467', '2022-04-04 18:29:34.415479', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'MEMBERS', 'ZHIDINGSHENPIREN', '指定审批人', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 2, 1, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (5, null, '2022-04-04 18:29:34.416028', '2022-04-04 18:29:34.416039', null, null, 0, 0, 0, 1, 1, 'CUSTOM', '', 'RADIO', '27924a83a1b9d239086e9724264a53e3', '审批意见', 'COL_6', 'REQUIRE', 'EMPTY', '', 'true', '[{"key":"true","name":"\\u901a\\u8fc7"},{"key":"false","name":"\\u62d2\\u7edd"}]', '{}', 4, 1, '', '{"code":"APPROVE_RESULT"}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (6, null, '2022-04-04 18:29:34.416599', '2022-04-04 18:29:34.416610', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', '63f03ddeb567ba12dd711db71ee46e66', '备注', 'COL_12', 'OPTION', 'EMPTY', '', '', '[]', '{}', 4, 1, '', '{}', 0, 0, '{}', '{"expressions":[{"value":"false","type":"RADIO","condition":"==","key":"27924a83a1b9d239086e9724264a53e3"}],"type":"and"}', 0, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (7, null, '2022-04-04 18:29:34.417170', '2022-04-04 18:29:34.417181', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', '71f9445928b83fd2aec3c2e0deea4889', '备注', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 4, 1, '', '{}', 0, 0, '{}', '{"expressions":[{"value":"true","type":"RADIO","condition":"==","key":"27924a83a1b9d239086e9724264a53e3"}],"type":"and"}', 0, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (8, null, '2022-04-04 18:29:34.417726', '2022-04-04 18:29:34.417737', null, null, 0, 0, 0, 1, 1, 'CUSTOM', '', 'RADIO', 'a00592c80f7febec616849b177a6cf5d', '审批意见', 'COL_6', 'REQUIRE', 'EMPTY', '', 'true', '[{"key":"true","name":"\\u901a\\u8fc7"},{"key":"false","name":"\\u62d2\\u7edd"}]', '{}', 5, 1, '', '{"code":"APPROVE_RESULT"}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (9, null, '2022-04-04 18:29:34.418294', '2022-04-04 18:29:34.418305', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', '94c49c3a5047dda38ed1e07fb53c025d', '备注', 'COL_12', 'OPTION', 'EMPTY', '', '', '[]', '{}', 5, 1, '', '{}', 0, 0, '{}', '{"expressions":[{"value":"false","type":"RADIO","condition":"==","key":"a00592c80f7febec616849b177a6cf5d"}],"type":"and"}', 0, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (10, null, '2022-04-04 18:29:34.418851', '2022-04-04 18:29:34.418862', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', '3d1fbe249001dd755c075418904be892', '备注', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 5, 1, '', '{}', 0, 0, '{}', '{"expressions":[{"value":"true","type":"RADIO","condition":"==","key":"a00592c80f7febec616849b177a6cf5d"}],"type":"and"}', 0, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (11, null, '2022-04-04 18:29:34.441572', '2022-04-04 18:29:34.441583', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 'STRING', 'title', '标题', 'COL_12', 'REQUIRE', 'EMPTY', '请输入标题', '', '[]', '{}', null, 2, '', '{}', 0, 0, '{}', '{}', 1, '', 'TABLE', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (12, null, '2022-04-04 18:29:34.442147', '2022-04-04 18:29:34.442158', null, null, 0, 1, 0, 1, 1, 'DATADICT', 'IMPACT', 'SELECT', 'impact', '影响范围', 'COL_6', 'REQUIRE', 'EMPTY', '请选择影响范围', '', '[]', '{"be_relied":["priority"]}', null, 2, '', '{}', 0, 0, '{}', '{}', 1, '', 'TABLE', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"SELECT","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (13, null, '2022-04-04 18:29:34.442709', '2022-04-04 18:29:34.442721', null, null, 0, 1, 0, 1, 1, 'DATADICT', 'URGENCY', 'SELECT', 'urgency', '紧急程度', 'COL_6', 'REQUIRE', 'EMPTY', '请选择紧急程度', '', '[]', '{"be_relied":["priority"]}', null, 2, '', '{}', 0, 0, '{}', '{}', 1, '', 'TABLE', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"SELECT","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (14, null, '2022-04-04 18:29:34.445983', '2022-04-04 18:29:34.445994', null, null, 0, 1, 0, 1, 1, 'API', '', 'SELECT', 'bk_biz_id', '关联业务', 'COL_6', 'REQUIRE', 'EMPTY', '请选择关联业务', '蓝盾', '[]', '{"rely_on":[]}', 7, 2, '', '{}', 1, 0, '{"key":"bk_biz_id","name":"bk_biz_name"}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"SELECT","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (15, null, '2022-04-04 18:29:34.446573', '2022-04-04 18:29:34.446584', null, null, 0, 0, 0, 1, 1, 'CUSTOM', '', 'RADIO', 'b416ef64ca8fc2939679a2acec276114', '审批意见', 'COL_6', 'REQUIRE', 'EMPTY', '', 'true', '[{"key":"true","name":"\\u901a\\u8fc7"},{"key":"false","name":"\\u62d2\\u7edd"}]', '{}', 9, 2, '', '{"code":"APPROVE_RESULT"}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (16, null, '2022-04-04 18:29:34.447143', '2022-04-04 18:29:34.447154', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', '214029a9156f17938fdc33cb8d50a457', '备注', 'COL_12', 'OPTION', 'EMPTY', '', '', '[]', '{}', 9, 2, '', '{}', 0, 0, '{}', '{"expressions":[{"value":"false","type":"RADIO","condition":"==","key":"b416ef64ca8fc2939679a2acec276114"}],"type":"and"}', 0, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (17, null, '2022-04-04 18:29:34.447703', '2022-04-04 18:29:34.447714', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', '029a9b5363d5b6c5ce3411deef8ecfd1', '备注', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 9, 2, '', '{}', 0, 0, '{}', '{"expressions":[{"value":"true","type":"RADIO","condition":"==","key":"b416ef64ca8fc2939679a2acec276114"}],"type":"and"}', 0, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (18, null, '2022-04-04 18:29:34.448269', '2022-04-04 18:29:34.448280', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'RICHTEXT', 'BIANGENGXIANGQING', '变更详情', 'COL_12', 'REQUIRE', 'EMPTY', '请填写变更的详细内容', '', '[]', '{}', 7, 2, '', '{}', 0, 1, '{}', '{}', 1, '按模板填写变更单', 'CUSTOM', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"RICHTEXT","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (19, null, '2022-04-04 18:29:34.448831', '2022-04-04 18:29:34.448842', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'DATETIME', 'YUQIBIANGENGSHIJIAN', '预期变更时间', 'COL_6', 'OPTION', 'EMPTY', '请选择预期的变更时间', '', '[]', '{}', 7, 2, '', '{}', 0, 1, '{}', '{}', 1, '请选择预期的变更时间', 'CUSTOM', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"DATETIME","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (20, null, '2022-04-04 18:29:34.449404', '2022-04-04 18:29:34.449415', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'SELECT', 'BIANGENGCHANGJING', '变更场景', 'COL_6', 'REQUIRE', 'EMPTY', '请选择变更的场景', '', '[{"key":"GATEWAY","name":"\\u7f51\\u5173"},{"key":"DOCKERHOST","name":"dockerhost"},{"key":"MICROSERVICE","name":"\\u5fae\\u670d\\u52a1"},{"key":"OTHER","name":"\\u5176\\u4ed6"}]', '{}', 7, 2, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"SELECT","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (21, null, '2022-04-04 18:29:34.449989', '2022-04-04 18:29:34.450000', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'RICHTEXT', 'JIAOFUXINXI', '备注', 'COL_12', 'OPTION', 'EMPTY', '', '', '[]', '{}', 10, 2, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"RICHTEXT","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (22, null, '2022-04-04 18:29:34.450565', '2022-04-04 18:29:34.450575', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'FILE', 'FUJIAN', '附件', 'COL_12', 'OPTION', 'EMPTY', '', '', '{}', '{}', 7, 2, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (23, null, '2022-04-04 18:29:34.451153', '2022-04-04 18:29:34.451164', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'RADIO', 'YANZHENGFANG', '验证方', 'COL_12', 'REQUIRE', 'EMPTY', '', 'KAIFAYANZHENG', '[{"key":"KAIFAYANZHENG","name":"\\u5f00\\u53d1\\u9a8c\\u8bc1"},{"key":"YUNWEIYANZHENG","name":"\\u8fd0\\u7ef4\\u9a8c\\u8bc1"},{"key":"YONGHUYANZHENG","name":"\\u7528\\u6237\\u9a8c\\u8bc1"},{"key":"CESHIYANZHENG","name":"\\u6d4b\\u8bd5\\u9a8c\\u8bc1"}]', '{}', 11, 2, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"RADIO","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (24, null, '2022-04-04 18:29:34.451758', '2022-04-04 18:29:34.451769', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'RADIO', 'YANZHENGJIEGUO', '验证结果', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[{"key":"TONGGUO","name":"\\u901a\\u8fc7"},{"key":"BUTONGGUO","name":"\\u4e0d\\u901a\\u8fc7"}]', '{}', 11, 2, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (25, null, '2022-04-04 18:29:34.452336', '2022-04-04 18:29:34.452347', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'RICHTEXT', 'BEIZHUSHUOMING', '备注说明', 'COL_12', 'OPTION', 'EMPTY', '', '<p>（如验证结果有异常，可在这里简要说明。）</p>', '[]', '{}', 11, 2, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"RICHTEXT","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (26, null, '2022-04-04 18:29:34.452893', '2022-04-04 18:29:34.452904', null, null, 0, 1, 1, 1, 0, 'DATADICT', 'PRIORITY', 'SELECT', 'priority', '优先级', 'COL_6', 'REQUIRE', 'EMPTY', '请选择优先级', '', '[]', '{"rely_on":["urgency","impact"]}', 7, 2, '', '{}', 0, 0, '{}', '{}', 1, '', 'TABLE', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"SELECT","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (27, null, '2022-04-04 18:29:34.453473', '2022-04-04 18:29:34.453484', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'RADIO', 'FABUCHULIREN', '发布处理人', 'COL_12', 'REQUIRE', 'EMPTY', '', 'YUNWEIFABU', '[{"key":"YUNWEIFABU","name":"\\u8fd0\\u7ef4\\u53d1\\u5e03"},{"key":"ZHINENGHUAFABU","name":"\\u804c\\u80fd\\u5316\\u53d1\\u5e03"}]', '{}', 10, 2, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"RADIO","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (28, null, '2022-04-04 18:29:34.454046', '2022-04-04 18:29:34.454057', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'RADIO', 'FABUFANGSHI', '发布方式', 'COL_12', 'REQUIRE', 'EMPTY', '', 'BIAOZHUNYUNWEI', '[{"key":"BIAOZHUNYUNWEI","name":"\\u6807\\u51c6\\u8fd0\\u7ef4"},{"key":"ZUOYEPINGTAI","name":"\\u4f5c\\u4e1a\\u5e73\\u53f0"},{"key":"LIUSHUIXIAN","name":"\\u6d41\\u6c34\\u7ebf"}]', '{}', 10, 2, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (29, null, '2022-04-04 18:29:34.454627', '2022-04-04 18:29:34.454638', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', 'CHULISHUOMING', '处理说明', 'COL_12', 'OPTION', 'EMPTY', '', '', '[]', '{}', 12, 2, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (30, null, '2022-04-04 18:29:34.455180', '2022-04-04 18:29:34.455191', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'RADIO', 'BUSHUJIEGUO', '部署结果', 'COL_12', 'REQUIRE', 'EMPTY', '', 'WANCHENG', '[{"key":"WANCHENG","name":"\\u5b8c\\u6210"},{"key":"QUXIAO","name":"\\u53d6\\u6d88"}]', '{}', 12, 2, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (31, null, '2022-04-04 18:29:34.968292', '2022-04-04 18:29:34.968317', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 'STRING', 'title', '标题', 'COL_12', 'REQUIRE', 'EMPTY', '请输入标题', '', '[]', '{}', null, 3, '', '{}', 0, 0, '{}', '{}', 1, '', 'TABLE', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (32, null, '2022-04-04 18:29:34.972310', '2022-04-04 18:29:34.972322', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'MEMBERS', 'APPROVER', '审批人', 'COL_12', 'REQUIRE', '', '', '', '[]', '{}', 14, 3, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (33, null, '2022-04-04 18:29:34.972942', '2022-04-04 18:29:34.972953', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', 'APPROVAL_CONTENT', '审批内容', 'COL_6', 'REQUIRE', '', '', '', '[]', '{}', 14, 3, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (34, null, '2022-04-04 18:29:34.977831', '2022-04-04 18:29:34.977842', null, null, 0, 0, 0, 1, 1, 'CUSTOM', '', 'RADIO', 'd458ade7820ef350d13f49f1135f70bd', '审批意见', 'COL_6', 'REQUIRE', 'EMPTY', '', 'true', '[{"key":"true","name":"\\u901a\\u8fc7"},{"key":"false","name":"\\u62d2\\u7edd"}]', '{}', 15, 3, '', '{"code":"APPROVE_RESULT"}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (35, null, '2022-04-04 18:29:34.978545', '2022-04-04 18:29:34.978556', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', 'e8616a0856df3e8348cda67a34ef266e', '备注', 'COL_12', 'OPTION', 'EMPTY', '', '', '[]', '{}', 15, 3, '', '{}', 0, 0, '{}', '{"expressions":[{"value":"false","type":"RADIO","condition":"==","key":"d458ade7820ef350d13f49f1135f70bd"}],"type":"and"}', 0, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (36, null, '2022-04-04 18:29:34.979261', '2022-04-04 18:29:34.979273', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', 'c5f3a39933bc2aa6af5ebb68898b49a6', '备注', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 15, 3, '', '{}', 0, 0, '{}', '{"expressions":[{"value":"true","type":"RADIO","condition":"==","key":"d458ade7820ef350d13f49f1135f70bd"}],"type":"and"}', 0, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (37, null, '2022-04-04 18:29:35.038712', '2022-04-04 18:29:35.038724', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 'STRING', 'title', '标题', 'COL_12', 'REQUIRE', 'EMPTY', '请输入标题', '', '[]', '{}', null, 4, '', '{}', 0, 0, '{}', '{}', 1, '', 'TABLE', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (38, null, '2022-04-04 18:29:35.039323', '2022-04-04 18:29:35.039335', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'STRING', 'application_type', '申请类型', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 18, 4, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"STRING","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (39, null, '2022-04-04 18:29:35.039903', '2022-04-04 18:29:35.039914', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'STRING', 'reason', '申请理由', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 18, 4, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"STRING","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (40, null, '2022-04-04 18:29:35.040495', '2022-04-04 18:29:35.040506', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'STRING', 'organization', '组织', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 18, 4, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"STRING","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (41, null, '2022-04-04 18:29:35.041068', '2022-04-04 18:29:35.041079', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'CUSTOM-FORM', 'content', '申请内容', 'COL_12', 'REQUIRE', 'EMPTY', '', '{
    "schemes": {},
    "form_data": []
}', '[]', '{}', 18, 4, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (42, null, '2022-04-04 18:29:35.041641', '2022-04-04 18:29:35.041652', null, null, 0, 0, 0, 1, 1, 'CUSTOM', '', 'RADIO', 'b48d699d8ebb63db91cd68837ae32509', '审批意见', 'COL_6', 'REQUIRE', 'EMPTY', '', 'true', '[{"key":"true","name":"\\u901a\\u8fc7"},{"key":"false","name":"\\u62d2\\u7edd"}]', '{}', 20, 4, '', '{"code":"APPROVE_RESULT"}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (43, null, '2022-04-04 18:29:35.042217', '2022-04-04 18:29:35.042228', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', '301ae3fb3123aaa2d28704fc83c86e45', '备注', 'COL_12', 'OPTION', 'EMPTY', '', '', '[]', '{}', 20, 4, '', '{}', 0, 0, '{}', '{"expressions":[{"value":"false","type":"RADIO","condition":"==","key":"b48d699d8ebb63db91cd68837ae32509"}],"type":"and"}', 0, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (44, null, '2022-04-04 18:29:35.042779', '2022-04-04 18:29:35.042789', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', 'bc4a4f1762f80e8a5800118f8c7a833b', '备注', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 20, 4, '', '{}', 0, 0, '{}', '{"expressions":[{"value":"true","type":"RADIO","condition":"==","key":"b48d699d8ebb63db91cd68837ae32509"}],"type":"and"}', 0, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (45, null, '2022-04-04 18:29:35.074983', '2022-04-04 18:29:35.074994', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 'STRING', 'title', '标题', 'COL_12', 'REQUIRE', 'EMPTY', '请输入标题', '', '[]', '{}', null, 5, '', '{}', 0, 0, '{}', '{}', 1, '', 'TABLE', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (46, null, '2022-04-04 18:29:35.075575', '2022-04-04 18:29:35.075586', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'STRING', 'application_type', '申请类型', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 22, 5, '', '{}', 0, 0, '{}', '{}', 1, '', 'TABLE', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"STRING","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (47, null, '2022-04-04 18:29:35.076160', '2022-04-04 18:29:35.076171', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'STRING', 'reason', '申请理由', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 22, 5, '', '{}', 0, 0, '{}', '{}', 1, '', 'TABLE', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"STRING","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (48, null, '2022-04-04 18:29:35.076727', '2022-04-04 18:29:35.076738', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'STRING', 'organization', '组织', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 22, 5, '', '{}', 0, 0, '{}', '{}', 1, '', 'TABLE', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"STRING","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (49, null, '2022-04-04 18:29:35.077298', '2022-04-04 18:29:35.077309', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'CUSTOM-FORM', 'content', '申请内容', 'COL_12', 'REQUIRE', 'EMPTY', '', '{
    "schemes": {},
    "form_data": []
}', '[]', '{}', 22, 5, '', '{}', 0, 0, '{}', '{}', 1, '', 'TABLE', '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (50, null, '2022-04-04 18:29:35.077856', '2022-04-04 18:29:35.077867', null, null, 0, 0, 0, 1, 1, 'CUSTOM', '', 'RADIO', '34a24bd158ff37cf571f2a1dedfff3ba', '审批意见', 'COL_6', 'REQUIRE', 'EMPTY', '', 'true', '[{"key":"true","name":"\\u901a\\u8fc7"},{"key":"false","name":"\\u62d2\\u7edd"}]', '{}', 24, 5, '', '{"code":"APPROVE_RESULT"}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (51, null, '2022-04-04 18:29:35.078468', '2022-04-04 18:29:35.078479', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', '9b40ecbe6bf43d986cd9ac20a3fdd001', '备注', 'COL_12', 'OPTION', 'EMPTY', '', '', '[]', '{}', 24, 5, '', '{}', 0, 0, '{}', '{"expressions":[{"value":"false","type":"RADIO","condition":"==","key":"34a24bd158ff37cf571f2a1dedfff3ba"}],"type":"and"}', 0, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (52, null, '2022-04-04 18:29:35.079044', '2022-04-04 18:29:35.079055', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', 'a989e058f79f13dcd056a54eb3104c13', '备注', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 24, 5, '', '{}', 0, 0, '{}', '{"expressions":[{"value":"true","type":"RADIO","condition":"==","key":"34a24bd158ff37cf571f2a1dedfff3ba"}],"type":"and"}', 0, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (53, null, '2022-04-04 18:29:35.187952', '2022-04-04 18:29:35.187964', null, null, 0, 1, 0, 1, 1, 'CUSTOM', '', 'STRING', 'title', '标题', 'COL_12', 'REQUIRE', 'EMPTY', '请输入标题', '', '[]', '{}', null, 6, '', '{}', 0, 0, '{}', '{}', 1, '', 'TABLE', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (54, null, '2022-04-04 18:29:35.191266', '2022-04-04 18:29:35.191278', null, null, 0, 1, 0, 1, 1, 'API', '', 'SELECT', 'bk_biz_id', '关联业务', 'COL_6', 'REQUIRE', 'EMPTY', '请选择关联业务', '', '[]', '{}', 26, 6, '', '{}', 2, 0, '{"name":"bk_biz_name","key":"bk_biz_id"}', '{}', 1, '', 'CUSTOM', '{}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (55, null, '2022-04-04 18:29:35.191853', '2022-04-04 18:29:35.191865', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'DATE', 'expect_access_data', '期待接入日期', 'COL_6', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 26, 6, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (56, null, '2022-04-04 18:29:35.192420', '2022-04-04 18:29:35.192432', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'INT', 'single_log_size', '单条日志大小(Bytes)', 'COL_6', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 26, 6, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"INT","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (57, null, '2022-04-04 18:29:35.192991', '2022-04-04 18:29:35.193002', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'INT', 'single_host_peak', '单机流量峰值（KB/S）', 'COL_6', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 26, 6, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"INT","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (58, null, '2022-04-04 18:29:35.193574', '2022-04-04 18:29:35.193586', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'INT', 'single_host_log_volume', '单机增长日志量', 'COL_6', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 26, 6, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (59, null, '2022-04-04 18:29:35.194138', '2022-04-04 18:29:35.194150', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'INT', 'expect_host_size', '预计接入主机数', 'COL_6', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 26, 6, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (60, null, '2022-04-04 18:29:35.194761', '2022-04-04 18:29:35.194772', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'INT', 'log_keep_days', '日志保留天数', 'COL_6', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 26, 6, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (61, null, '2022-04-04 18:29:35.195321', '2022-04-04 18:29:35.195333', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', 'apply_reason', '申请原因', 'COL_12', 'OPTION', 'EMPTY', '', '', '[]', '{}', 26, 6, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (62, null, '2022-04-04 18:29:35.195874', '2022-04-04 18:29:35.195885', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'RADIO', 'can_use_independent_es_cluster', '是否使用独立ES集群', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[{"key":"false","name":"\\u4e0d\\u4f7f\\u7528"},{"key":"true","name":"\\u4f7f\\u7528"}]', '{}', 28, 6, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"RADIO","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (63, null, '2022-04-04 18:29:35.196472', '2022-04-04 18:29:35.196483', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'STRING', 'hot_data_days', '热数据天数', 'COL_6', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 26, 6, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"STRING","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (64, null, '2022-04-04 18:29:35.197035', '2022-04-04 18:29:35.197046', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'CUSTOM-FORM', 'collector_detail', '采集详情', 'COL_12', 'OPTION', 'EMPTY', '', '{
    "schemes": {},
    "form_data": []
}', '[]', '{}', 26, 6, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (65, null, '2022-04-04 18:29:35.197598', '2022-04-04 18:29:35.197609', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'CUSTOM-FORM', 'capacity_formula', '容量公式', 'COL_12', 'OPTION', 'EMPTY', '', '{
    "schemes": {},
    "form_data": []
}', '[]', '{}', 26, 6, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"CUSTOM-FORM","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (66, null, '2022-04-04 18:29:35.198172', '2022-04-04 18:29:35.198183', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'RADIO', 'approval_result', '审批意见', 'COL_12', 'REQUIRE', 'EMPTY', '', 'true', '[{"key":"true","name":"\\u901a\\u8fc7"},{"key":"false","name":"\\u62d2\\u7edd"}]', '{}', 28, 6, '', '{}', 0, 0, '{}', '{}', 1, '', 'CUSTOM', '{"rule":{"expressions":[{"condition":"","key":"","source":"field","type":"RADIO","value":""}],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (67, null, '2022-04-04 18:29:35.198743', '2022-04-04 18:29:35.198754', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', 'remark_1', '备注', 'COL_12', 'OPTION', 'EMPTY', '', '', '[]', '{}', 28, 6, '', '{}', 0, 0, '{}', '{"type":"and","expressions":[{"key":"approval_result","condition":"==","value":"false","type":"RADIO"}]}', 0, '', 'CUSTOM', '{"rule":{"expressions":[],"type":"and"}}');
INSERT INTO bk_itsm.workflow_field (id, creator, create_at, update_at, updated_by, end_at, is_deleted, is_builtin, is_readonly, is_valid, display, source_type, source_uri, type, `key`, name, layout, validate_type, regex, `desc`, `default`, choice, related_fields, state_id, workflow_id, custom_regex, meta, api_instance_id, is_tips, kv_relation, show_conditions, show_type, tips, source, regex_config) VALUES (68, null, '2022-04-04 18:29:35.199336', '2022-04-04 18:29:35.199347', null, null, 0, 0, 0, 1, 0, 'CUSTOM', '', 'TEXT', 'remark_2', '备注', 'COL_12', 'REQUIRE', 'EMPTY', '', '', '[]', '{}', 28, 6, '', '{}', 0, 0, '{}', '{"type":"and","expressions":[{"key":"approval_result","condition":"==","value":"true","type":"RADIO"}]}', 0, '', 'CUSTOM', '{"rule":{"expressions":[],"type":"and"}}');
