create table auth_permission
(
    id              int auto_increment
        primary key,
    name            varchar(255) not null,
    content_type_id int          not null,
    codename        varchar(100) not null,
    constraint auth_permission_content_type_id_codename_01ab375a_uniq
        unique (content_type_id, codename),
    constraint auth_permission_content_type_id_2f476e4b_fk_django_co
        foreign key (content_type_id) references django_content_type (id)
);

INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (1, 'Can add log entry', 3, 'add_logentry');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (2, 'Can change log entry', 3, 'change_logentry');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (3, 'Can delete log entry', 3, 'delete_logentry');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (4, 'Can view log entry', 3, 'view_logentry');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (5, 'Can add permission', 4, 'add_permission');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (6, 'Can change permission', 4, 'change_permission');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (7, 'Can delete permission', 4, 'delete_permission');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (8, 'Can view permission', 4, 'view_permission');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (9, 'Can add group', 5, 'add_group');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (10, 'Can change group', 5, 'change_group');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (11, 'Can delete group', 5, 'delete_group');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (12, 'Can view group', 5, 'view_group');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (13, 'Can add content type', 6, 'add_contenttype');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (14, 'Can change content type', 6, 'change_contenttype');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (15, 'Can delete content type', 6, 'delete_contenttype');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (16, 'Can view content type', 6, 'view_contenttype');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (17, 'Can add session', 7, 'add_session');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (18, 'Can change session', 7, 'change_session');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (19, 'Can delete session', 7, 'delete_session');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (20, 'Can view session', 7, 'view_session');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (21, 'Can add site', 8, 'add_site');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (22, 'Can change site', 8, 'change_site');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (23, 'Can delete site', 8, 'delete_site');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (24, 'Can view site', 8, 'view_site');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (25, 'Can add user', 1, 'add_user');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (26, 'Can change user', 1, 'change_user');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (27, 'Can delete user', 1, 'delete_user');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (28, 'Can view user', 1, 'view_user');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (29, 'Can add user property', 9, 'add_userproperty');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (30, 'Can change user property', 9, 'change_userproperty');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (31, 'Can delete user property', 9, 'delete_userproperty');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (32, 'Can view user property', 9, 'view_userproperty');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (33, 'Can add user proxy', 2, 'add_userproxy');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (34, 'Can change user proxy', 2, 'change_userproxy');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (35, 'Can delete user proxy', 2, 'delete_userproxy');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (36, 'Can view user proxy', 2, 'view_userproxy');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (37, 'Can add verify info', 10, 'add_verifyinfo');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (38, 'Can change verify info', 10, 'change_verifyinfo');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (39, 'Can delete verify info', 10, 'delete_verifyinfo');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (40, 'Can view verify info', 10, 'view_verifyinfo');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (41, 'Can add 业务 Business', 11, 'add_business');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (42, 'Can change 业务 Business', 11, 'change_business');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (43, 'Can delete 业务 Business', 11, 'delete_business');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (44, 'Can view 业务 Business', 11, 'view_business');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (45, 'Can get business', 11, 'get_business');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (46, 'Can manage business', 11, 'manage_business');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (47, 'Can add 业务用户组 BusinessGroupMembership', 12, 'add_businessgroupmembership');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (48, 'Can change 业务用户组 BusinessGroupMembership', 12, 'change_businessgroupmembership');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (49, 'Can delete 业务用户组 BusinessGroupMembership', 12, 'delete_businessgroupmembership');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (50, 'Can view 业务用户组 BusinessGroupMembership', 12, 'view_businessgroupmembership');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (51, 'Can add 用户默认业务 UserBusiness', 13, 'add_userbusiness');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (52, 'Can change 用户默认业务 UserBusiness', 13, 'change_userbusiness');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (53, 'Can delete 用户默认业务 UserBusiness', 13, 'delete_userbusiness');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (54, 'Can view 用户默认业务 UserBusiness', 13, 'view_userbusiness');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (55, 'Can add 环境变量 EnvironmentVariables', 14, 'add_environmentvariables');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (56, 'Can change 环境变量 EnvironmentVariables', 14, 'change_environmentvariables');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (57, 'Can delete 环境变量 EnvironmentVariables', 14, 'delete_environmentvariables');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (58, 'Can view 环境变量 EnvironmentVariables', 14, 'view_environmentvariables');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (59, 'Can add 项目 Project', 15, 'add_project');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (60, 'Can change 项目 Project', 15, 'change_project');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (61, 'Can delete 项目 Project', 15, 'delete_project');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (62, 'Can view 项目 Project', 15, 'view_project');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (63, 'Can add 用户默认项目 UserDefaultProject', 16, 'add_userdefaultproject');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (64, 'Can change 用户默认项目 UserDefaultProject', 16, 'change_userdefaultproject');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (65, 'Can delete 用户默认项目 UserDefaultProject', 16, 'delete_userdefaultproject');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (66, 'Can view 用户默认项目 UserDefaultProject', 16, 'view_userdefaultproject');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (67, 'Can add 用户访问项目计数 ProjectCounter', 17, 'add_projectcounter');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (68, 'Can change 用户访问项目计数 ProjectCounter', 17, 'change_projectcounter');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (69, 'Can delete 用户访问项目计数 ProjectCounter', 17, 'delete_projectcounter');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (70, 'Can view 用户访问项目计数 ProjectCounter', 17, 'view_projectcounter');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (71, 'Can add 项目配置 ProjectConfig', 18, 'add_projectconfig');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (72, 'Can change 项目配置 ProjectConfig', 18, 'change_projectconfig');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (73, 'Can delete 项目配置 ProjectConfig', 18, 'delete_projectconfig');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (74, 'Can view 项目配置 ProjectConfig', 18, 'view_projectconfig');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (75, 'Can add 基于项目的组件 ProjectBasedComponent', 19, 'add_projectbasedcomponent');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (76, 'Can change 基于项目的组件 ProjectBasedComponent', 19, 'change_projectbasedcomponent');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (77, 'Can delete 基于项目的组件 ProjectBasedComponent', 19, 'delete_projectbasedcomponent');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (78, 'Can view 基于项目的组件 ProjectBasedComponent', 19, 'view_projectbasedcomponent');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (79, 'Can add 集群资源筛选方案', 20, 'add_resourceconfig');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (80, 'Can change 集群资源筛选方案', 20, 'change_resourceconfig');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (81, 'Can delete 集群资源筛选方案', 20, 'delete_resourceconfig');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (82, 'Can view 集群资源筛选方案', 20, 'view_resourceconfig');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (83, 'Can add 人员分组设置 StaffGroupSet', 21, 'add_staffgroupset');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (84, 'Can change 人员分组设置 StaffGroupSet', 21, 'change_staffgroupset');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (85, 'Can delete 人员分组设置 StaffGroupSet', 21, 'delete_staffgroupset');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (86, 'Can view 人员分组设置 StaffGroupSet', 21, 'view_staffgroupset');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (87, 'Can add 流程模板 TaskTemplate', 22, 'add_tasktemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (88, 'Can change 流程模板 TaskTemplate', 22, 'change_tasktemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (89, 'Can delete 流程模板 TaskTemplate', 22, 'delete_tasktemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (90, 'Can view 流程模板 TaskTemplate', 22, 'view_tasktemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (91, 'Can add 流程实例 TaskFlowInstance', 23, 'add_taskflowinstance');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (92, 'Can change 流程实例 TaskFlowInstance', 23, 'change_taskflowinstance');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (93, 'Can delete 流程实例 TaskFlowInstance', 23, 'delete_taskflowinstance');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (94, 'Can view 流程实例 TaskFlowInstance', 23, 'view_taskflowinstance');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (95, 'Can add 轻应用 AppMaker', 24, 'add_appmaker');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (96, 'Can change 轻应用 AppMaker', 24, 'change_appmaker');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (97, 'Can delete 轻应用 AppMaker', 24, 'delete_appmaker');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (98, 'Can view 轻应用 AppMaker', 24, 'view_appmaker');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (99, 'Can add 职能化认领单 FunctionTask', 25, 'add_functiontask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (100, 'Can change 职能化认领单 FunctionTask', 25, 'change_functiontask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (101, 'Can delete 职能化认领单 FunctionTask', 25, 'delete_functiontask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (102, 'Can view 职能化认领单 FunctionTask', 25, 'view_functiontask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (103, 'Can add 用户收藏 Collection', 26, 'add_collection');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (104, 'Can change 用户收藏 Collection', 26, 'change_collection');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (105, 'Can delete 用户收藏 Collection', 26, 'delete_collection');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (106, 'Can view 用户收藏 Collection', 26, 'view_collection');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (107, 'Can add 任务操作记录', 27, 'add_taskoperaterecord');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (108, 'Can change 任务操作记录', 27, 'change_taskoperaterecord');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (109, 'Can delete 任务操作记录', 27, 'delete_taskoperaterecord');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (110, 'Can view 任务操作记录', 27, 'view_taskoperaterecord');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (111, 'Can add 模版操作记录', 28, 'add_templateoperaterecord');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (112, 'Can change 模版操作记录', 28, 'change_templateoperaterecord');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (113, 'Can delete 模版操作记录', 28, 'delete_templateoperaterecord');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (114, 'Can view 模版操作记录', 28, 'view_templateoperaterecord');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (115, 'Can add 公共流程模板 CommonTemplate', 29, 'add_commontemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (116, 'Can change 公共流程模板 CommonTemplate', 29, 'change_commontemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (117, 'Can delete 公共流程模板 CommonTemplate', 29, 'delete_commontemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (118, 'Can view 公共流程模板 CommonTemplate', 29, 'view_commontemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (119, 'Can add 用户标签 Label', 30, 'add_label');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (120, 'Can change 用户标签 Label', 30, 'change_label');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (121, 'Can delete 用户标签 Label', 30, 'delete_label');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (122, 'Can view 用户标签 Label', 30, 'view_label');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (123, 'Can add 模版标签关系 TemplateLabelRelation', 31, 'add_templatelabelrelation');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (124, 'Can change 模版标签关系 TemplateLabelRelation', 31, 'change_templatelabelrelation');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (125, 'Can delete 模版标签关系 TemplateLabelRelation', 31, 'delete_templatelabelrelation');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (126, 'Can view 模版标签关系 TemplateLabelRelation', 31, 'view_templatelabelrelation');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (127, 'Can add 周期任务 PeriodicTask', 32, 'add_periodictask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (128, 'Can change 周期任务 PeriodicTask', 32, 'change_periodictask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (129, 'Can delete 周期任务 PeriodicTask', 32, 'delete_periodictask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (130, 'Can view 周期任务 PeriodicTask', 32, 'view_periodictask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (131, 'Can add periodic task history', 33, 'add_periodictaskhistory');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (132, 'Can change periodic task history', 33, 'change_periodictaskhistory');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (133, 'Can delete periodic task history', 33, 'delete_periodictaskhistory');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (134, 'Can view periodic task history', 33, 'view_periodictaskhistory');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (135, 'Can add 远程包源缓存 CachePackageSource', 34, 'add_cachepackagesource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (136, 'Can change 远程包源缓存 CachePackageSource', 34, 'change_cachepackagesource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (137, 'Can delete 远程包源缓存 CachePackageSource', 34, 'delete_cachepackagesource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (138, 'Can view 远程包源缓存 CachePackageSource', 34, 'view_cachepackagesource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (139, 'Can add FS远程包源 FileSystemOriginalSource', 35, 'add_filesystemoriginalsource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (140, 'Can change FS远程包源 FileSystemOriginalSource', 35, 'change_filesystemoriginalsource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (141, 'Can delete FS远程包源 FileSystemOriginalSource', 35, 'delete_filesystemoriginalsource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (142, 'Can view FS远程包源 FileSystemOriginalSource', 35, 'view_filesystemoriginalsource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (143, 'Can add GIT远程包源 GitRepoOriginalSource', 36, 'add_gitrepooriginalsource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (144, 'Can change GIT远程包源 GitRepoOriginalSource', 36, 'change_gitrepooriginalsource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (145, 'Can delete GIT远程包源 GitRepoOriginalSource', 36, 'delete_gitrepooriginalsource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (146, 'Can view GIT远程包源 GitRepoOriginalSource', 36, 'view_gitrepooriginalsource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (147, 'Can add S3远程包源 S3OriginalSource', 37, 'add_s3originalsource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (148, 'Can change S3远程包源 S3OriginalSource', 37, 'change_s3originalsource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (149, 'Can delete S3远程包源 S3OriginalSource', 37, 'delete_s3originalsource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (150, 'Can view S3远程包源 S3OriginalSource', 37, 'view_s3originalsource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (151, 'Can add 远程包源同步任务 SyncTask', 38, 'add_synctask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (152, 'Can change 远程包源同步任务 SyncTask', 38, 'change_synctask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (153, 'Can delete 远程包源同步任务 SyncTask', 38, 'delete_synctask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (154, 'Can view 远程包源同步任务 SyncTask', 38, 'view_synctask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (155, 'Can add Pipeline实例', 39, 'add_pipelineinstance');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (156, 'Can change Pipeline实例', 39, 'change_pipelineinstance');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (157, 'Can delete Pipeline实例', 39, 'delete_pipelineinstance');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (158, 'Can view Pipeline实例', 39, 'view_pipelineinstance');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (159, 'Can add Pipeline模板', 40, 'add_pipelinetemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (160, 'Can change Pipeline模板', 40, 'change_pipelinetemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (161, 'Can delete Pipeline模板', 40, 'delete_pipelinetemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (162, 'Can view Pipeline模板', 40, 'view_pipelinetemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (163, 'Can add 模板快照', 41, 'add_snapshot');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (164, 'Can change 模板快照', 41, 'change_snapshot');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (165, 'Can delete 模板快照', 41, 'delete_snapshot');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (166, 'Can view 模板快照', 41, 'view_snapshot');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (167, 'Can add template scheme', 42, 'add_templatescheme');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (168, 'Can change template scheme', 42, 'change_templatescheme');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (169, 'Can delete template scheme', 42, 'delete_templatescheme');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (170, 'Can view template scheme', 42, 'view_templatescheme');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (171, 'Can add tree info', 43, 'add_treeinfo');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (172, 'Can change tree info', 43, 'change_treeinfo');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (173, 'Can delete tree info', 43, 'delete_treeinfo');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (174, 'Can view tree info', 43, 'view_treeinfo');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (175, 'Can add template version', 44, 'add_templateversion');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (176, 'Can change template version', 44, 'change_templateversion');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (177, 'Can delete template version', 44, 'delete_templateversion');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (178, 'Can view template version', 44, 'view_templateversion');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (179, 'Can add template relationship', 45, 'add_templaterelationship');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (180, 'Can change template relationship', 45, 'change_templaterelationship');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (181, 'Can delete template relationship', 45, 'delete_templaterelationship');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (182, 'Can view template relationship', 45, 'view_templaterelationship');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (183, 'Can add template current version', 46, 'add_templatecurrentversion');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (184, 'Can change template current version', 46, 'change_templatecurrentversion');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (185, 'Can delete template current version', 46, 'delete_templatecurrentversion');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (186, 'Can view template current version', 46, 'view_templatecurrentversion');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (187, 'Can add 组件 Component', 47, 'add_componentmodel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (188, 'Can change 组件 Component', 47, 'change_componentmodel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (189, 'Can delete 组件 Component', 47, 'delete_componentmodel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (190, 'Can view 组件 Component', 47, 'view_componentmodel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (191, 'Can add Variable变量', 48, 'add_variablemodel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (192, 'Can change Variable变量', 48, 'change_variablemodel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (193, 'Can delete Variable变量', 48, 'delete_variablemodel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (194, 'Can view Variable变量', 48, 'view_variablemodel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (195, 'Can add data', 49, 'add_data');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (196, 'Can change data', 49, 'change_data');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (197, 'Can delete data', 49, 'delete_data');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (198, 'Can view data', 49, 'view_data');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (199, 'Can add history', 50, 'add_history');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (200, 'Can change history', 50, 'change_history');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (201, 'Can delete history', 50, 'delete_history');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (202, 'Can view history', 50, 'view_history');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (203, 'Can add history data', 51, 'add_historydata');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (204, 'Can change history data', 51, 'change_historydata');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (205, 'Can delete history data', 51, 'delete_historydata');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (206, 'Can view history data', 51, 'view_historydata');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (207, 'Can add node relationship', 52, 'add_noderelationship');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (208, 'Can change node relationship', 52, 'change_noderelationship');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (209, 'Can delete node relationship', 52, 'delete_noderelationship');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (210, 'Can view node relationship', 52, 'view_noderelationship');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (211, 'Can add pipeline model', 53, 'add_pipelinemodel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (212, 'Can change pipeline model', 53, 'change_pipelinemodel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (213, 'Can delete pipeline model', 53, 'delete_pipelinemodel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (214, 'Can view pipeline model', 53, 'view_pipelinemodel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (215, 'Can add pipeline process', 54, 'add_pipelineprocess');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (216, 'Can change pipeline process', 54, 'change_pipelineprocess');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (217, 'Can delete pipeline process', 54, 'delete_pipelineprocess');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (218, 'Can view pipeline process', 54, 'view_pipelineprocess');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (219, 'Can add process celery task', 55, 'add_processcelerytask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (220, 'Can change process celery task', 55, 'change_processcelerytask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (221, 'Can delete process celery task', 55, 'delete_processcelerytask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (222, 'Can view process celery task', 55, 'view_processcelerytask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (223, 'Can add process snapshot', 56, 'add_processsnapshot');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (224, 'Can change process snapshot', 56, 'change_processsnapshot');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (225, 'Can delete process snapshot', 56, 'delete_processsnapshot');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (226, 'Can view process snapshot', 56, 'view_processsnapshot');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (227, 'Can add schedule service', 57, 'add_scheduleservice');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (228, 'Can change schedule service', 57, 'change_scheduleservice');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (229, 'Can delete schedule service', 57, 'delete_scheduleservice');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (230, 'Can view schedule service', 57, 'view_scheduleservice');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (231, 'Can add status', 58, 'add_status');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (232, 'Can change status', 58, 'change_status');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (233, 'Can delete status', 58, 'delete_status');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (234, 'Can view status', 58, 'view_status');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (235, 'Can add sub process relationship', 59, 'add_subprocessrelationship');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (236, 'Can change sub process relationship', 59, 'change_subprocessrelationship');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (237, 'Can delete sub process relationship', 59, 'delete_subprocessrelationship');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (238, 'Can view sub process relationship', 59, 'view_subprocessrelationship');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (239, 'Can add function switch', 60, 'add_functionswitch');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (240, 'Can change function switch', 60, 'change_functionswitch');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (241, 'Can delete function switch', 60, 'delete_functionswitch');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (242, 'Can view function switch', 60, 'view_functionswitch');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (243, 'Can add schedule celery task', 61, 'add_schedulecelerytask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (244, 'Can change schedule celery task', 61, 'change_schedulecelerytask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (245, 'Can delete schedule celery task', 61, 'delete_schedulecelerytask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (246, 'Can view schedule celery task', 61, 'view_schedulecelerytask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (247, 'Can add node celery task', 62, 'add_nodecelerytask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (248, 'Can change node celery task', 62, 'change_nodecelerytask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (249, 'Can delete node celery task', 62, 'delete_nodecelerytask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (250, 'Can view node celery task', 62, 'view_nodecelerytask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (251, 'Can add data snapshot', 63, 'add_datasnapshot');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (252, 'Can change data snapshot', 63, 'change_datasnapshot');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (253, 'Can delete data snapshot', 63, 'delete_datasnapshot');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (254, 'Can view data snapshot', 63, 'view_datasnapshot');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (255, 'Can add multi callback data', 64, 'add_multicallbackdata');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (256, 'Can change multi callback data', 64, 'change_multicallbackdata');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (257, 'Can delete multi callback data', 64, 'delete_multicallbackdata');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (258, 'Can view multi callback data', 64, 'view_multicallbackdata');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (259, 'Can add send failed celery task', 65, 'add_sendfailedcelerytask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (260, 'Can change send failed celery task', 65, 'change_sendfailedcelerytask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (261, 'Can delete send failed celery task', 65, 'delete_sendfailedcelerytask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (262, 'Can view send failed celery task', 65, 'view_sendfailedcelerytask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (263, 'Can add log entry', 66, 'add_logentry');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (264, 'Can change log entry', 66, 'change_logentry');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (265, 'Can delete log entry', 66, 'delete_logentry');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (266, 'Can view log entry', 66, 'view_logentry');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (267, 'Can add Pipeline标准插件执行数据', 67, 'add_componentexecutedata');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (268, 'Can change Pipeline标准插件执行数据', 67, 'change_componentexecutedata');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (269, 'Can delete Pipeline标准插件执行数据', 67, 'delete_componentexecutedata');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (270, 'Can view Pipeline标准插件执行数据', 67, 'view_componentexecutedata');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (271, 'Can add Pipeline标准插件被引用数据', 68, 'add_componentintemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (272, 'Can change Pipeline标准插件被引用数据', 68, 'change_componentintemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (273, 'Can delete Pipeline标准插件被引用数据', 68, 'delete_componentintemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (274, 'Can view Pipeline标准插件被引用数据', 68, 'view_componentintemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (275, 'Can add Pipeline实例引用数据', 69, 'add_instanceinpipeline');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (276, 'Can change Pipeline实例引用数据', 69, 'change_instanceinpipeline');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (277, 'Can delete Pipeline实例引用数据', 69, 'delete_instanceinpipeline');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (278, 'Can view Pipeline实例引用数据', 69, 'view_instanceinpipeline');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (279, 'Can add Pipeline模板引用数据', 70, 'add_templateinpipeline');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (280, 'Can change Pipeline模板引用数据', 70, 'change_templateinpipeline');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (281, 'Can delete Pipeline模板引用数据', 70, 'delete_templateinpipeline');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (282, 'Can view Pipeline模板引用数据', 70, 'view_templateinpipeline');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (283, 'Can add crontab', 71, 'add_crontabschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (284, 'Can change crontab', 71, 'change_crontabschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (285, 'Can delete crontab', 71, 'delete_crontabschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (286, 'Can view crontab', 71, 'view_crontabschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (287, 'Can add djcelery periodic task', 72, 'add_djceleryperiodictask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (288, 'Can change djcelery periodic task', 72, 'change_djceleryperiodictask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (289, 'Can delete djcelery periodic task', 72, 'delete_djceleryperiodictask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (290, 'Can view djcelery periodic task', 72, 'view_djceleryperiodictask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (291, 'Can add dj celery periodic tasks', 73, 'add_djceleryperiodictasks');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (292, 'Can change dj celery periodic tasks', 73, 'change_djceleryperiodictasks');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (293, 'Can delete dj celery periodic tasks', 73, 'delete_djceleryperiodictasks');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (294, 'Can view dj celery periodic tasks', 73, 'view_djceleryperiodictasks');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (295, 'Can add interval', 74, 'add_intervalschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (296, 'Can change interval', 74, 'change_intervalschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (297, 'Can delete interval', 74, 'delete_intervalschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (298, 'Can view interval', 74, 'view_intervalschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (299, 'Can add periodic task', 75, 'add_periodictask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (300, 'Can change periodic task', 75, 'change_periodictask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (301, 'Can delete periodic task', 75, 'delete_periodictask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (302, 'Can view periodic task', 75, 'view_periodictask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (303, 'Can add periodic task history', 76, 'add_periodictaskhistory');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (304, 'Can change periodic task history', 76, 'change_periodictaskhistory');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (305, 'Can delete periodic task history', 76, 'delete_periodictaskhistory');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (306, 'Can view periodic task history', 76, 'view_periodictaskhistory');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (307, 'Can add file system source', 77, 'add_filesystemsource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (308, 'Can change file system source', 77, 'change_filesystemsource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (309, 'Can delete file system source', 77, 'delete_filesystemsource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (310, 'Can view file system source', 77, 'view_filesystemsource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (311, 'Can add git repo source', 78, 'add_gitreposource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (312, 'Can change git repo source', 78, 'change_gitreposource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (313, 'Can delete git repo source', 78, 'delete_gitreposource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (314, 'Can view git repo source', 78, 'view_gitreposource');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (315, 'Can add s3 source', 79, 'add_s3source');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (316, 'Can change s3 source', 79, 'change_s3source');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (317, 'Can delete s3 source', 79, 'delete_s3source');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (318, 'Can view s3 source', 79, 'view_s3source');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (319, 'Can add signal', 80, 'add_signal');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (320, 'Can change signal', 80, 'change_signal');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (321, 'Can delete signal', 80, 'delete_signal');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (322, 'Can view signal', 80, 'view_signal');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (323, 'Can add 流程实例节点 NodeInInstance', 81, 'add_nodeininstance');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (324, 'Can change 流程实例节点 NodeInInstance', 81, 'change_nodeininstance');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (325, 'Can delete 流程实例节点 NodeInInstance', 81, 'delete_nodeininstance');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (326, 'Can view 流程实例节点 NodeInInstance', 81, 'view_nodeininstance');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (327, 'Can add 流程模板节点 NodeInTemplate', 82, 'add_nodeintemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (328, 'Can change 流程模板节点 NodeInTemplate', 82, 'change_nodeintemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (329, 'Can delete 流程模板节点 NodeInTemplate', 82, 'delete_nodeintemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (330, 'Can view 流程模板节点 NodeInTemplate', 82, 'view_nodeintemplate');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (331, 'Can add 标签 Label', 83, 'add_label');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (332, 'Can change 标签 Label', 83, 'change_label');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (333, 'Can delete 标签 Label', 83, 'delete_label');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (334, 'Can view 标签 Label', 83, 'view_label');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (335, 'Can add 标签分组 LabelGroup', 84, 'add_labelgroup');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (336, 'Can change 标签分组 LabelGroup', 84, 'change_labelgroup');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (337, 'Can delete 标签分组 LabelGroup', 84, 'delete_labelgroup');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (338, 'Can view 标签分组 LabelGroup', 84, 'view_labelgroup');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (339, 'Can add 流程实例节点标签 NodeInInstanceAttrLabel', 85, 'add_nodeininstanceattrlabel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (340, 'Can change 流程实例节点标签 NodeInInstanceAttrLabel', 85, 'change_nodeininstanceattrlabel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (341, 'Can delete 流程实例节点标签 NodeInInstanceAttrLabel', 85, 'delete_nodeininstanceattrlabel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (342, 'Can view 流程实例节点标签 NodeInInstanceAttrLabel', 85, 'view_nodeininstanceattrlabel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (343, 'Can add 流程模板节点标签 NodeInTemplateAttrLabel', 86, 'add_nodeintemplateattrlabel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (344, 'Can change 流程模板节点标签 NodeInTemplateAttrLabel', 86, 'change_nodeintemplateattrlabel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (345, 'Can delete 流程模板节点标签 NodeInTemplateAttrLabel', 86, 'delete_nodeintemplateattrlabel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (346, 'Can view 流程模板节点标签 NodeInTemplateAttrLabel', 86, 'view_nodeintemplateattrlabel');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (347, 'Can add deprecated plugin', 87, 'add_deprecatedplugin');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (348, 'Can change deprecated plugin', 87, 'change_deprecatedplugin');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (349, 'Can delete deprecated plugin', 87, 'delete_deprecatedplugin');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (350, 'Can view deprecated plugin', 87, 'view_deprecatedplugin');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (351, 'Can add 微信用户', 88, 'add_bkweixinuser');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (352, 'Can change 微信用户', 88, 'change_bkweixinuser');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (353, 'Can delete 微信用户', 88, 'delete_bkweixinuser');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (354, 'Can view 微信用户', 88, 'view_bkweixinuser');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (355, 'Can add 版本日志访问记录', 89, 'add_versionlogvisited');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (356, 'Can change 版本日志访问记录', 89, 'change_versionlogvisited');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (357, 'Can delete 版本日志访问记录', 89, 'delete_versionlogvisited');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (358, 'Can view 版本日志访问记录', 89, 'view_versionlogvisited');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (359, 'Can add upload module file tag', 90, 'add_uploadmodulefiletag');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (360, 'Can change upload module file tag', 90, 'change_uploadmodulefiletag');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (361, 'Can delete upload module file tag', 90, 'delete_uploadmodulefiletag');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (362, 'Can view upload module file tag', 90, 'view_uploadmodulefiletag');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (363, 'Can add upload ticket', 91, 'add_uploadticket');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (364, 'Can change upload ticket', 91, 'change_uploadticket');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (365, 'Can delete upload ticket', 91, 'delete_uploadticket');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (366, 'Can view upload ticket', 91, 'view_uploadticket');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (367, 'Can add crontab', 92, 'add_crontabschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (368, 'Can change crontab', 92, 'change_crontabschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (369, 'Can delete crontab', 92, 'delete_crontabschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (370, 'Can view crontab', 92, 'view_crontabschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (371, 'Can add interval', 93, 'add_intervalschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (372, 'Can change interval', 93, 'change_intervalschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (373, 'Can delete interval', 93, 'delete_intervalschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (374, 'Can view interval', 93, 'view_intervalschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (375, 'Can add periodic task', 94, 'add_periodictask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (376, 'Can change periodic task', 94, 'change_periodictask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (377, 'Can delete periodic task', 94, 'delete_periodictask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (378, 'Can view periodic task', 94, 'view_periodictask');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (379, 'Can add periodic tasks', 95, 'add_periodictasks');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (380, 'Can change periodic tasks', 95, 'change_periodictasks');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (381, 'Can delete periodic tasks', 95, 'delete_periodictasks');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (382, 'Can view periodic tasks', 95, 'view_periodictasks');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (383, 'Can add solar event', 96, 'add_solarschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (384, 'Can change solar event', 96, 'change_solarschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (385, 'Can delete solar event', 96, 'delete_solarschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (386, 'Can view solar event', 96, 'view_solarschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (387, 'Can add clocked', 97, 'add_clockedschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (388, 'Can change clocked', 97, 'change_clockedschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (389, 'Can delete clocked', 97, 'delete_clockedschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (390, 'Can view clocked', 97, 'view_clockedschedule');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (391, 'Can add task result', 98, 'add_taskresult');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (392, 'Can change task result', 98, 'change_taskresult');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (393, 'Can delete task result', 98, 'delete_taskresult');
INSERT INTO bk_sops.auth_permission (id, name, content_type_id, codename) VALUES (394, 'Can view task result', 98, 'view_taskresult');
