create table saas_action
(
    pk              int unsigned auto_increment
        primary key,
    system_id       varchar(32)                             not null,
    id              varchar(32)                             not null,
    name            varchar(255)                            not null,
    name_en         varchar(255)                            not null,
    description     varchar(1024) default ''                not null,
    description_en  varchar(1024) default ''                not null,
    related_actions text                                    not null,
    type            varchar(32)   default ''                not null,
    version         int unsigned  default 0                 null,
    created_at      timestamp     default CURRENT_TIMESTAMP not null,
    updated_at      timestamp     default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP,
    constraint idx_uk_system_action_id
        unique (system_id, id)
);

INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (1, 'bk_paas', 'access_developer_center', '访问开发者中心', 'access developer center', '一个用户是否能访问开发者中心', 'Is allowed to access the developer center', 'null', 'create', 1, '2022-04-04 06:23:08', '2022-04-04 06:23:08');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (2, 'bk_paas', 'manage_smart', '管理Smart应用', 'manage smart', '一个用户可以管理所有的smart应用', 'Is allowed to manage all smart apps', '["access_developer_center"]', '', 1, '2022-04-04 06:23:08', '2022-04-04 06:23:08');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (3, 'bk_paas', 'ops_system', '系统维护', 'system ops', '一个用户可以对PaaS进行系统维护', 'Is the ops of the paas system', '["access_developer_center"]', '', 1, '2022-04-04 06:23:08', '2022-04-04 06:23:08');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (4, 'bk_paas', 'manage_apigateway', 'API网关维护', 'manage apigateway', '一个用户可以维护api网关', 'Is the manager of API Gateway', '["access_developer_center"]', '', 1, '2022-04-04 06:23:08', '2022-04-04 06:23:08');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (5, 'bk_paas', 'develop_app', '开发SaaS应用及外链应用', 'develop app', '一个用户是否能够开发SaaS 及外链应用', 'Is allowed to develop SaaS app and ext-link app', '["access_developer_center"]', '', 1, '2022-04-04 06:23:08', '2022-04-04 06:23:08');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (6, 'bk_usermgr', 'manage_field', '用户字段管理', 'Manage Field', '字段新增、删除、编辑', 'manage_field is...', 'null', 'edit', 1, '2022-04-04 06:24:16', '2022-04-04 06:24:16');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (7, 'bk_usermgr', 'view_audit', '审计信息查看', 'Review Audit', '用户操作审计信息查看', 'view_audit is...', 'null', 'view', 1, '2022-04-04 06:24:16', '2022-04-04 06:24:16');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (8, 'bk_usermgr', 'create_local_category', '本地用户目录新建', 'Create Local Category', '本地用户目录的新建和管理权限', 'create_local_category is...', 'null', 'create', 1, '2022-04-04 06:24:16', '2022-04-04 06:24:16');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (9, 'bk_usermgr', 'create_ldap_category', 'LDAP目录新建', 'Create LDAP Category', 'LDAP目录的新建和管理权限', 'create_ldap_category is...', 'null', 'create', 1, '2022-04-04 06:24:16', '2022-04-04 06:24:16');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (10, 'bk_usermgr', 'create_mad_category', 'MAD目录新建', 'Create MAD Category', 'MAD目录的新建和管理权限', 'create_mad_category is...', 'null', 'create', 1, '2022-04-04 06:24:16', '2022-04-04 06:24:16');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (11, 'bk_usermgr', 'create_custom_category', '自定义目录新建', 'Create Custom Category', '自定义目录的新建和管理权限', 'create_custom_category is...', 'null', 'create', 1, '2022-04-04 06:24:16', '2022-04-04 06:24:16');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (12, 'bk_usermgr', 'manage_category', '用户目录管理', 'Manage Category', '对目录本身的管理权限，包括该目录下组织架构的管理权限', 'manage_category is...', '["view_category"]', 'edit', 1, '2022-04-04 06:24:16', '2022-04-04 06:24:16');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (13, 'bk_usermgr', 'manage_department', '组织和成员管理', 'Manage Department and Profile', '组织、子组织、组织成员管理权限', 'manage_department is...', '["view_department"]', 'edit', 1, '2022-04-04 06:24:16', '2022-04-04 06:24:16');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (14, 'bk_usermgr', 'view_category', '用户目录查看', 'View category', '用户目录查看', 'view_category is...', 'null', 'view', 1, '2022-04-04 06:24:16', '2022-04-04 06:24:16');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (15, 'bk_usermgr', 'view_department', '组织及用户查看', 'View department & profiles', '组织、子组织、组织成员查看权限', 'create_local_category is...', 'null', 'create', 1, '2022-04-04 06:24:16', '2022-04-04 06:24:16');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (16, 'bk_itsm', 'project_create', '创建项目', 'Create Project', '项目的新建', '', 'null', 'create', 1, '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (17, 'bk_itsm', 'project_view', '项目查看', 'Project View', '查看项目的详情', '', 'null', 'view', 1, '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (18, 'bk_itsm', 'project_edit', '项目编辑', 'Project Edit', '编辑项目内容', '', 'null', 'edit', 1, '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (19, 'bk_itsm', 'service_create', '服务创建', 'Create Service', '服务的新建', '', 'null', 'create', 1, '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (20, 'bk_itsm', 'service_manage', '服务管理', 'Manage Service', '对某个服务资源实例的查看、修改、删除', '', 'null', 'manage', 1, '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (21, 'bk_itsm', 'sla_manage', '服务协议管理', 'Manage SLA', '包含服务模式，服务协议，优先级，单据状态的管理（增删改查）', '', 'null', 'manage', 1, '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (22, 'bk_itsm', 'workflow_create', '流程创建', 'Create Workflow', '对应创建流程，版本还原，导入操作', '', 'null', 'create', 1, '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (23, 'bk_itsm', 'workflow_manage', '流程管理', 'Manage Workflow', '流程的编辑，预览，导出，删除的权限', '', 'null', 'manage', 1, '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (24, 'bk_itsm', 'workflow_deploy', '流程部署', 'Deploy Workflow', '流程部署版本权限', '', 'null', 'create', 1, '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (25, 'bk_itsm', 'flow_version_restore', '流程版本还原', 'Restore Workflow Version', '还原指定流程版本资源实例到流程设计阶段', '', 'null', 'create', 1, '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (26, 'bk_itsm', 'flow_version_manage', '流程版本管理', 'Manage Workflow Version', '流程版本资源的删除和查看详情', '', 'null', 'manage', 1, '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (27, 'bk_itsm', 'flow_element_manage', '流程元素管理', 'Manage Workflow Element', '对流程中用到的基础资源进行管理，如：API，基础模型，公共字段，任务模板，公共触发器，数据字典。', '', 'null', 'view', 1, '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (28, 'bk_itsm', 'system_settings_manage', '系统配置管理', 'Manage System Settings', '全局基础配置管理。如不同模块的启停配置，接口日志查看，附件存储目录管理。', '', 'null', 'view', 1, '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (29, 'bk_itsm', 'role_create', '角色创建', 'Create Role', '创建通用角色', '', 'null', 'create', 1, '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (30, 'bk_itsm', 'role_manage', '角色管理', 'Manage Role', '具体的用户角色的编辑，删除和查看', '', 'null', 'delete', 1, '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (31, 'bk_itsm', 'ticket_view', '工单查看', 'View Ticket', '查看某个服务资源下工单的权限', '', 'null', 'view', 1, '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (32, 'bk_itsm', 'knowledge_manage', '知识管理', 'Manage Knowledge', '对知识库中所有文章进行编辑,删除和管理。', '', 'null', 'manage', 1, '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (33, 'bk_itsm', 'operational_data_view', '运营数据查看', 'View Operational Data', '查看运营数据的权限', '', 'null', 'view', 1, '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (34, 'bk_sops', 'project_create', '创建项目', 'create project', '', '', 'null', 'create', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (35, 'bk_sops', 'project_view', '项目查看', 'Project View', '', '', 'null', 'view', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (36, 'bk_sops', 'project_edit', '项目编辑', 'Project Edit', '', '', '["project_view"]', 'edit', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (37, 'bk_sops', 'flow_create', '流程创建', 'Flow Create', '', '', '["project_view"]', 'create', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (38, 'bk_sops', 'project_fast_create_task', '一次性任务新建', 'Task fast create', '', '', 'null', 'create', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (39, 'bk_sops', 'flow_view', '流程查看', 'Flow View', '', '', '["project_view"]', 'view', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (40, 'bk_sops', 'flow_edit', '流程编辑', 'Flow Edit', '', '', '["project_view","flow_view"]', 'edit', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (41, 'bk_sops', 'flow_delete', '流程删除', 'Flow Delete', '', '', 'null', 'delete', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (42, 'bk_sops', 'flow_create_task', '流程新建任务', 'Flow Create Task', '', '', '["project_view","flow_view"]', 'create', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (43, 'bk_sops', 'flow_create_mini_app', '流程新建轻应用', 'Flow Create Mini Application', '', '', '["project_view","flow_view"]', 'create', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (44, 'bk_sops', 'flow_create_periodic_task', '流程新建周期任务', 'Flow Create Periodic Task', '', '', '["project_view","flow_view"]', 'create', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (45, 'bk_sops', 'task_view', '任务查看', 'Task View', '', '', '["project_view"]', 'view', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (46, 'bk_sops', 'task_edit', '任务编辑', 'Task Edit', '', '', '["project_view","task_view"]', 'edit', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (47, 'bk_sops', 'task_operate', '任务操作', 'Task Operate', '', '', '["project_view","task_view"]', 'edit', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (48, 'bk_sops', 'task_claim', '任务认领', 'Task Claim', '', '', '["project_view","task_view"]', 'edit', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (49, 'bk_sops', 'task_delete', '任务删除', 'Task Delete', '', '', 'null', 'delete', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (50, 'bk_sops', 'task_clone', '任务克隆', 'Task Clone', '', '', '["project_view"]', 'create', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (51, 'bk_sops', 'common_flow_create', '公共流程新建', 'Common Flow Create', '', '', 'null', 'create', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (52, 'bk_sops', 'common_flow_view', '公共流程查看', 'Common Flow View', '', '', 'null', 'view', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (53, 'bk_sops', 'common_flow_edit', '公共流程编辑', 'Common Flow Edit', '', '', '["common_flow_view"]', 'edit', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (54, 'bk_sops', 'common_flow_delete', '公共流程删除', 'Common Flow Delete', '', '', 'null', 'delete', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (55, 'bk_sops', 'common_flow_create_task', '公共流程新建任务', 'Common Flow Create Task', '', '', '["project_view","common_flow_view"]', 'create', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (56, 'bk_sops', 'common_flow_create_periodic_task', '公共流程新建周期任务', 'Common Flow Create Periodic Task', '', '', '["project_view","common_flow_view"]', 'create', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (57, 'bk_sops', 'mini_app_view', '轻应用查看', 'Mini Application View', '', '', '["project_view"]', 'view', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (58, 'bk_sops', 'mini_app_edit', '轻应用编辑', 'Mini Application Edit', '', '', '["project_view","mini_app_view"]', 'edit', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (59, 'bk_sops', 'mini_app_delete', '轻应用删除', 'Mini Application Delete', '', '', '["project_view"]', 'delete', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (60, 'bk_sops', 'mini_app_create_task', '轻应用创建任务', 'Mini Application Create Task', '', '', '["project_view","mini_app_view"]', 'create', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (61, 'bk_sops', 'periodic_task_view', '周期任务查看', 'Periodic Task View', '', '', '["project_view"]', 'view', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (62, 'bk_sops', 'periodic_task_edit', '周期任务编辑', 'Periodic Task Edit', '', '', '["project_view","periodic_task_view"]', 'edit', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (63, 'bk_sops', 'periodic_task_delete', '周期任务删除', 'Periodic Task Delete', '', '', '["project_view"]', 'delete', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (64, 'bk_sops', 'admin_view', '后台管理查看', 'Admin Center View', '', '', 'null', 'view', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (65, 'bk_sops', 'admin_edit', '后台管理编辑', 'Admin Center Edit', '', '', '["admin_view"]', 'edit', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (66, 'bk_sops', 'audit_view', '审计中心查看', 'Audit Center View', '', '', 'null', 'view', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (67, 'bk_sops', 'function_view', '职能化中心查看', 'Function Center View', '', '', 'null', 'view', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (68, 'bk_sops', 'statistics_view', '数据统计查看', 'Statistics View', '', '', 'null', 'view', 1, '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (69, 'bk_nodeman', 'cloud_view', '云区域查看', 'Cloud View', '', '', 'null', 'view', 1, '2022-04-04 06:43:23', '2022-04-04 06:43:23');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (70, 'bk_nodeman', 'cloud_edit', '云区域编辑', 'Cloud Edit', '', '', '["cloud_view"]', 'edit', 1, '2022-04-04 06:43:23', '2022-04-04 06:43:23');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (71, 'bk_nodeman', 'cloud_delete', '云区域删除', 'Cloud Delete', '', '', '["cloud_view"]', 'delete', 1, '2022-04-04 06:43:23', '2022-04-04 06:43:23');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (72, 'bk_nodeman', 'cloud_create', '云区域创建', 'Cloud Create', '', '', 'null', 'create', 1, '2022-04-04 06:43:23', '2022-04-04 06:43:23');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (73, 'bk_nodeman', 'ap_view', '接入点查看', 'Ap View', '', '', 'null', 'view', 1, '2022-04-04 06:43:23', '2022-04-04 06:43:23');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (74, 'bk_nodeman', 'ap_edit', '接入点编辑', 'Ap Edit', '', '', '["ap_view"]', 'edit', 1, '2022-04-04 06:43:23', '2022-04-04 06:43:23');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (75, 'bk_nodeman', 'ap_delete', '接入点删除', 'Ap Delete', '', '', '["ap_view"]', 'delete', 1, '2022-04-04 06:43:23', '2022-04-04 06:43:23');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (76, 'bk_nodeman', 'ap_create', '接入点创建', 'Ap Create', '', '', 'null', 'create', 1, '2022-04-04 06:43:23', '2022-04-04 06:43:23');
INSERT INTO bkiam.saas_action (pk, system_id, id, name, name_en, description, description_en, related_actions, type, version, created_at, updated_at) VALUES (77, 'bk_nodeman', 'globe_task_config', '任务配置', 'Globe Task Config', '', '', 'null', 'view', 1, '2022-04-04 06:43:23', '2022-04-04 06:43:23');
