create table saas_action_resource_type
(
    pk                          int unsigned auto_increment
        primary key,
    action_system_id            varchar(32)                            not null,
    action_id                   varchar(32)                            not null,
    resource_type_system_id     varchar(32)                            not null,
    resource_type_id            varchar(32)                            not null,
    name_alias                  varchar(255) default ''                not null,
    name_alias_en               varchar(255) default ''                not null,
    selection_mode              varchar(32)  default ''                not null,
    related_instance_selections text                                   not null,
    created_at                  timestamp    default CURRENT_TIMESTAMP not null,
    updated_at                  timestamp    default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP
);

create index idx_action
    on saas_action_resource_type (action_system_id, action_id);

INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (1, 'bk_paas', 'develop_app', 'bk_paas', 'app', '', '', 'instance', '[{"system_id":"bk_paas","id":"app_view","ignore_iam_path":false}]', '2022-04-04 06:23:08', '2022-04-04 06:23:08');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (4, 'bk_usermgr', 'view_category', 'bk_usermgr', 'category', '目录', 'category', 'instance', '[{"system_id":"bk_usermgr","id":"category","ignore_iam_path":false}]', '2022-04-04 06:24:16', '2022-04-04 06:24:16');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (5, 'bk_usermgr', 'manage_category', 'bk_usermgr', 'category', '目录', 'category', 'instance', '[{"system_id":"bk_usermgr","id":"category","ignore_iam_path":false}]', '2022-04-04 06:24:16', '2022-04-04 06:24:16');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (6, 'bk_usermgr', 'view_department', 'bk_usermgr', 'department', '组织', 'department', 'instance', '[{"system_id":"bk_usermgr","id":"department","ignore_iam_path":false}]', '2022-04-04 06:24:16', '2022-04-04 06:24:16');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (7, 'bk_usermgr', 'manage_department', 'bk_usermgr', 'department', '组织', 'department', 'instance', '[{"system_id":"bk_usermgr","id":"department","ignore_iam_path":false}]', '2022-04-04 06:24:16', '2022-04-04 06:24:16');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (53, 'bk_itsm', 'project_view', 'bk_itsm', 'project', '', '', 'instance', '[{"system_id":"bk_itsm","id":"project_list","ignore_iam_path":false}]', '2022-04-04 06:29:21', '2022-04-04 06:29:21');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (54, 'bk_itsm', 'project_edit', 'bk_itsm', 'project', '', '', 'instance', '[{"system_id":"bk_itsm","id":"project_list","ignore_iam_path":false}]', '2022-04-04 06:29:21', '2022-04-04 06:29:21');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (55, 'bk_itsm', 'service_create', 'bk_itsm', 'project', '', '', 'instance', '[{"system_id":"bk_itsm","id":"project_list","ignore_iam_path":false}]', '2022-04-04 06:29:21', '2022-04-04 06:29:21');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (56, 'bk_itsm', 'service_manage', 'bk_itsm', 'service', '', '', 'instance', '[{"ignore_iam_path":true,"system_id":"bk_itsm","id":"service_list"}]', '2022-04-04 06:29:21', '2022-04-04 06:29:21');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (57, 'bk_itsm', 'sla_manage', 'bk_itsm', 'project', '', '', 'instance', '[{"id":"project_list","ignore_iam_path":false,"system_id":"bk_itsm"}]', '2022-04-04 06:29:21', '2022-04-04 06:29:21');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (58, 'bk_itsm', 'workflow_create', 'bk_itsm', 'project', '', '', 'instance', '[{"system_id":"bk_itsm","id":"project_list","ignore_iam_path":false}]', '2022-04-04 06:29:21', '2022-04-04 06:29:21');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (59, 'bk_itsm', 'workflow_manage', 'bk_itsm', 'workflow', '', '', 'instance', '[{"system_id":"bk_itsm","id":"workflow_list","ignore_iam_path":true}]', '2022-04-04 06:29:21', '2022-04-04 06:29:21');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (60, 'bk_itsm', 'workflow_deploy', 'bk_itsm', 'workflow', '', '', 'instance', '[{"system_id":"bk_itsm","id":"workflow_list","ignore_iam_path":true}]', '2022-04-04 06:29:21', '2022-04-04 06:29:21');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (61, 'bk_itsm', 'flow_version_restore', 'bk_itsm', 'flow_version', '', '', 'instance', '[{"system_id":"bk_itsm","id":"flow_version_list","ignore_iam_path":true}]', '2022-04-04 06:29:21', '2022-04-04 06:29:21');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (62, 'bk_itsm', 'flow_version_manage', 'bk_itsm', 'flow_version', '', '', 'instance', '[{"system_id":"bk_itsm","id":"flow_version_list","ignore_iam_path":true}]', '2022-04-04 06:29:21', '2022-04-04 06:29:21');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (63, 'bk_itsm', 'flow_element_manage', 'bk_itsm', 'project', '', '', 'instance', '[{"system_id":"bk_itsm","id":"project_list","ignore_iam_path":false}]', '2022-04-04 06:29:21', '2022-04-04 06:29:21');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (64, 'bk_itsm', 'system_settings_manage', 'bk_itsm', 'project', '', '', 'instance', '[{"system_id":"bk_itsm","id":"project_list","ignore_iam_path":false}]', '2022-04-04 06:29:21', '2022-04-04 06:29:21');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (65, 'bk_itsm', 'role_create', 'bk_itsm', 'project', '', '', 'instance', '[{"system_id":"bk_itsm","id":"project_list","ignore_iam_path":false}]', '2022-04-04 06:29:21', '2022-04-04 06:29:21');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (66, 'bk_itsm', 'role_manage', 'bk_itsm', 'role', '', '', 'instance', '[{"system_id":"bk_itsm","id":"role_list","ignore_iam_path":true}]', '2022-04-04 06:29:21', '2022-04-04 06:29:21');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (67, 'bk_itsm', 'ticket_view', 'bk_itsm', 'service', '', '', 'instance', '[{"system_id":"bk_itsm","id":"service_list","ignore_iam_path":true}]', '2022-04-04 06:29:21', '2022-04-04 06:29:21');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (68, 'bk_sops', 'project_view', 'bk_sops', 'project', '', '', 'instance', '[{"id":"project","ignore_iam_path":false,"system_id":"bk_sops"}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (69, 'bk_sops', 'project_edit', 'bk_sops', 'project', '', '', 'instance', '[{"system_id":"bk_sops","id":"project","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (70, 'bk_sops', 'flow_create', 'bk_sops', 'project', '', '', 'instance', '[{"system_id":"bk_sops","id":"project","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (71, 'bk_sops', 'project_fast_create_task', 'bk_sops', 'project', '', '', 'instance', '[{"system_id":"bk_sops","id":"project","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (72, 'bk_sops', 'flow_view', 'bk_sops', 'flow', '', '', 'instance', '[{"system_id":"bk_sops","id":"flow","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (73, 'bk_sops', 'flow_edit', 'bk_sops', 'flow', '', '', 'instance', '[{"system_id":"bk_sops","id":"flow","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (74, 'bk_sops', 'flow_delete', 'bk_sops', 'flow', '', '', 'instance', '[{"system_id":"bk_sops","id":"flow","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (75, 'bk_sops', 'flow_create_task', 'bk_sops', 'flow', '', '', 'instance', '[{"system_id":"bk_sops","id":"flow","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (76, 'bk_sops', 'flow_create_mini_app', 'bk_sops', 'flow', '', '', 'instance', '[{"ignore_iam_path":false,"system_id":"bk_sops","id":"flow"}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (77, 'bk_sops', 'flow_create_periodic_task', 'bk_sops', 'flow', '', '', 'instance', '[{"system_id":"bk_sops","id":"flow","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (78, 'bk_sops', 'task_view', 'bk_sops', 'task', '', '', 'all', '[{"system_id":"bk_sops","id":"task","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (79, 'bk_sops', 'task_edit', 'bk_sops', 'task', '', '', 'all', '[{"system_id":"bk_sops","id":"task","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (80, 'bk_sops', 'task_operate', 'bk_sops', 'task', '', '', 'all', '[{"system_id":"bk_sops","id":"task","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (81, 'bk_sops', 'task_claim', 'bk_sops', 'task', '', '', 'all', '[{"system_id":"bk_sops","id":"task","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (82, 'bk_sops', 'task_delete', 'bk_sops', 'task', '', '', 'all', '[{"system_id":"bk_sops","id":"task","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (83, 'bk_sops', 'task_clone', 'bk_sops', 'task', '', '', 'all', '[{"id":"task","ignore_iam_path":false,"system_id":"bk_sops"}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (84, 'bk_sops', 'common_flow_view', 'bk_sops', 'common_flow', '', '', 'instance', '[{"system_id":"bk_sops","id":"common_flow","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (85, 'bk_sops', 'common_flow_edit', 'bk_sops', 'common_flow', '', '', 'instance', '[{"system_id":"bk_sops","id":"common_flow","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (86, 'bk_sops', 'common_flow_delete', 'bk_sops', 'common_flow', '', '', 'instance', '[{"id":"common_flow","ignore_iam_path":false,"system_id":"bk_sops"}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (87, 'bk_sops', 'common_flow_create_task', 'bk_sops', 'common_flow', '', '', 'instance', '[{"system_id":"bk_sops","id":"common_flow","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (88, 'bk_sops', 'common_flow_create_task', 'bk_sops', 'project', '', '', 'instance', '[{"ignore_iam_path":false,"system_id":"bk_sops","id":"project"}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (89, 'bk_sops', 'common_flow_create_periodic_task', 'bk_sops', 'common_flow', '', '', 'instance', '[{"id":"common_flow","ignore_iam_path":false,"system_id":"bk_sops"}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (90, 'bk_sops', 'common_flow_create_periodic_task', 'bk_sops', 'project', '', '', 'instance', '[{"system_id":"bk_sops","id":"project","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (91, 'bk_sops', 'mini_app_view', 'bk_sops', 'mini_app', '', '', 'instance', '[{"ignore_iam_path":false,"system_id":"bk_sops","id":"mini_app"}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (92, 'bk_sops', 'mini_app_edit', 'bk_sops', 'mini_app', '', '', 'instance', '[{"system_id":"bk_sops","id":"mini_app","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (93, 'bk_sops', 'mini_app_delete', 'bk_sops', 'mini_app', '', '', 'instance', '[{"system_id":"bk_sops","id":"mini_app","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (94, 'bk_sops', 'mini_app_create_task', 'bk_sops', 'mini_app', '', '', 'instance', '[{"system_id":"bk_sops","id":"mini_app","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (95, 'bk_sops', 'periodic_task_view', 'bk_sops', 'periodic_task', '', '', 'instance', '[{"id":"periodic_task","ignore_iam_path":false,"system_id":"bk_sops"}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (96, 'bk_sops', 'periodic_task_edit', 'bk_sops', 'periodic_task', '', '', 'instance', '[{"system_id":"bk_sops","id":"periodic_task","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (97, 'bk_sops', 'periodic_task_delete', 'bk_sops', 'periodic_task', '', '', 'instance', '[{"system_id":"bk_sops","id":"periodic_task","ignore_iam_path":false}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (110, 'bk_nodeman', 'cloud_view', 'bk_nodeman', 'cloud', '', '', 'instance', '[{"system_id":"bk_nodeman","id":"cloud_instance_selection","ignore_iam_path":false}]', '2022-04-04 06:49:41', '2022-04-04 06:49:41');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (111, 'bk_nodeman', 'cloud_edit', 'bk_nodeman', 'cloud', '', '', 'instance', '[{"ignore_iam_path":false,"system_id":"bk_nodeman","id":"cloud_instance_selection"}]', '2022-04-04 06:49:41', '2022-04-04 06:49:41');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (112, 'bk_nodeman', 'cloud_delete', 'bk_nodeman', 'cloud', '', '', 'instance', '[{"system_id":"bk_nodeman","id":"cloud_instance_selection","ignore_iam_path":false}]', '2022-04-04 06:49:41', '2022-04-04 06:49:41');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (113, 'bk_nodeman', 'ap_view', 'bk_nodeman', 'ap', '', '', 'instance', '[{"system_id":"bk_nodeman","id":"ap_instance_selection","ignore_iam_path":false}]', '2022-04-04 06:49:41', '2022-04-04 06:49:41');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (114, 'bk_nodeman', 'ap_edit', 'bk_nodeman', 'ap', '', '', 'instance', '[{"ignore_iam_path":false,"system_id":"bk_nodeman","id":"ap_instance_selection"}]', '2022-04-04 06:49:41', '2022-04-04 06:49:41');
INSERT INTO bkiam.saas_action_resource_type (pk, action_system_id, action_id, resource_type_system_id, resource_type_id, name_alias, name_alias_en, selection_mode, related_instance_selections, created_at, updated_at) VALUES (115, 'bk_nodeman', 'ap_delete', 'bk_nodeman', 'ap', '', '', 'instance', '[{"system_id":"bk_nodeman","id":"ap_instance_selection","ignore_iam_path":false}]', '2022-04-04 06:49:41', '2022-04-04 06:49:41');
