create table saas_system_config
(
    pk         int unsigned auto_increment
        primary key,
    system_id  varchar(32)                           not null,
    name       varchar(32)                           not null,
    type       varchar(32) default 'json'            not null,
    value      text                                  not null,
    created_at timestamp   default CURRENT_TIMESTAMP not null,
    updated_at timestamp   default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP,
    constraint idx_uk_system_name
        unique (system_id, name)
);

INSERT INTO bkiam.saas_system_config (pk, system_id, name, type, value, created_at, updated_at) VALUES (1, 'bk_paas', 'action_groups', 'json', '[{"name":"访问权限","name_en":"Access Permissions","actions":[{"id":"access_developer_center"}]},{"name":"开发者权限","name_en":"Developer Permissions","actions":[{"id":"develop_app"}]},{"name":"管理权限","name_en":"Admin Permissions","actions":[{"id":"manage_smart"},{"id":"ops_system"},{"id":"manage_apigateway"}]}]', '2022-04-04 06:23:08', '2022-04-04 06:23:08');
INSERT INTO bkiam.saas_system_config (pk, system_id, name, type, value, created_at, updated_at) VALUES (2, 'bk_paas', 'resource_creator_actions', 'json', '{"mode":"system","config":[{"id":"app","actions":[{"id":"develop_app","required":true}]}]}', '2022-04-04 06:23:08', '2022-04-04 06:23:08');
INSERT INTO bkiam.saas_system_config (pk, system_id, name, type, value, created_at, updated_at) VALUES (3, 'bk_usermgr', 'resource_creator_actions', 'json', '{"mode":"system","config":[{"id":"category","actions":[{"id":"manage_category","required":true},{"id":"view_category","required":true}]}]}', '2022-04-04 06:24:16', '2022-04-04 06:24:16');
INSERT INTO bkiam.saas_system_config (pk, system_id, name, type, value, created_at, updated_at) VALUES (4, 'bk_usermgr', 'action_groups', 'json', '[{"name":"组织和成员","name_en":"Department And Profile","actions":[{"id":"manage_department"},{"id":"view_department"}]},{"name":"用户目录","name_en":"Category","actions":[{"id":"create_local_category"},{"id":"create_ldap_category"},{"id":"create_mad_category"},{"id":"create_custom_category"},{"id":"manage_category"},{"id":"view_category"}]},{"name":"全局","name_en":"Global","actions":[{"id":"manage_field"}]},{"name":"运营统计","name_en":"Operation Statistic","actions":[{"id":"view_audit"}]}]', '2022-04-04 06:24:16', '2022-04-04 06:24:16');
INSERT INTO bkiam.saas_system_config (pk, system_id, name, type, value, created_at, updated_at) VALUES (5, 'bk_itsm', 'action_groups', 'json', '[{"name":"项目","name_en":"Project","actions":[{"id":"project_create"},{"id":"project_view"},{"id":"project_edit"},{"id":"system_settings_manage"}],"sub_groups":[{"name":"服务","name_en":"Service","actions":[{"id":"service_create"},{"id":"service_manage"},{"id":"sla_manage"}]},{"name":"流程","name_en":"Flow","actions":[{"id":"workflow_create"},{"id":"workflow_manage"},{"id":"workflow_deploy"},{"id":"flow_version_restore"},{"id":"flow_version_manage"},{"id":"flow_element_manage"}]},{"name":"角色","name_en":"Role","actions":[{"id":"role_create"},{"id":"role_manage"}]},{"name":"工单","name_en":"Ticket","actions":[{"id":"ticket_view"}]}]},{"name":"其他","name_en":"Others","actions":[{"id":"knowledge_manage"},{"id":"operational_data_view"}]}]', '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_system_config (pk, system_id, name, type, value, created_at, updated_at) VALUES (6, 'bk_itsm', 'resource_creator_actions', 'json', '{"mode":"system","config":[{"id":"project","actions":[{"id":"project_edit","required":true},{"id":"project_view","required":true},{"id":"service_create","required":true},{"id":"workflow_create","required":true},{"id":"role_create","required":true}]},{"id":"service","actions":[{"id":"service_manage","required":true},{"id":"ticket_view","required":true}]},{"id":"workflow","actions":[{"id":"workflow_manage","required":true},{"id":"workflow_deploy","required":true}]},{"id":"flow_version","actions":[{"id":"flow_version_restore","required":true},{"id":"flow_version_manage","required":true}]},{"id":"role","actions":[{"id":"role_manage","required":true}]}]}', '2022-04-04 06:29:20', '2022-04-04 06:29:20');
INSERT INTO bkiam.saas_system_config (pk, system_id, name, type, value, created_at, updated_at) VALUES (7, 'bk_itsm', 'common_actions', 'json', '[{"name":"服务管理员","name_en":"service_superuser","actions":[{"id":"project_view"},{"id":"service_create"},{"id":"workflow_create"},{"id":"flow_element_manage"},{"id":"role_create"}]},{"name":"系统配置管理","name_en":"system_manager","actions":[{"id":"project_view"},{"id":"system_settings_manage"},{"id":"knowledge_manage"}]},{"name":"单据查看","name_en":"ticket_view","actions":[{"id":"ticket_view"}]},{"name":"统计信息查看","name_en":"operational_data_view","actions":[{"id":"ticket_view"},{"id":"operational_data_view"}]}]', '2022-04-04 06:29:25', '2022-04-04 06:29:25');
INSERT INTO bkiam.saas_system_config (pk, system_id, name, type, value, created_at, updated_at) VALUES (8, 'bk_sops', 'action_groups', 'json', '[{"name":"项目","name_en":"Project","actions":[{"id":"project_create"},{"id":"project_view"},{"id":"project_edit"},{"id":"project_fast_create_task"}],"sub_groups":[{"name":"流程模板","name_en":"Flow","actions":[{"id":"flow_create"},{"id":"flow_view"},{"id":"flow_edit"},{"id":"flow_delete"},{"id":"flow_create_task"},{"id":"flow_create_mini_app"},{"id":"flow_create_periodic_task"}]},{"name":"任务实例","name_en":"Task","actions":[{"id":"task_view"},{"id":"task_operate"},{"id":"task_edit"},{"id":"task_claim"},{"id":"task_delete"},{"id":"task_clone"}]},{"name":"轻应用","name_en":"Mini App","actions":[{"id":"mini_app_view"},{"id":"mini_app_edit"},{"id":"mini_app_delete"},{"id":"mini_app_create_task"}]},{"name":"周期任务","name_en":"Periodic Task","actions":[{"id":"periodic_task_view"},{"id":"periodic_task_edit"},{"id":"periodic_task_delete"}]}]},{"name":"公共流程","name_en":"Common Flow","actions":[{"id":"common_flow_create"},{"id":"common_flow_view"},{"id":"common_flow_edit"},{"id":"common_flow_delete"},{"id":"common_flow_create_task"},{"id":"common_flow_create_periodic_task"}]},{"name":"管理员","name_en":"Admin","actions":[{"id":"admin_view"},{"id":"admin_edit"}]},{"name":"审计","name_en":"Audit","actions":[{"id":"audit_view"}]},{"name":"职能化","name_en":"function","actions":[{"id":"function_view"}]},{"name":"数据统计","name_en":"Statistics","actions":[{"id":"statistics_view"}]}]', '2022-04-04 06:38:05', '2022-04-04 06:38:05');
INSERT INTO bkiam.saas_system_config (pk, system_id, name, type, value, created_at, updated_at) VALUES (9, 'bk_sops', 'resource_creator_actions', 'json', '{"mode":"system","config":[{"id":"project","actions":[{"id":"project_fast_create_task","required":false},{"id":"flow_create","required":false},{"id":"project_edit","required":false},{"id":"project_view","required":false}],"sub_resource_types":[{"id":"flow","actions":[{"id":"flow_create_periodic_task","required":false},{"id":"flow_create_mini_app","required":false},{"id":"flow_create_task","required":false},{"id":"flow_delete","required":false},{"id":"flow_edit","required":false},{"id":"flow_view","required":false}]},{"id":"mini_app","actions":[{"id":"mini_app_create_task","required":false},{"id":"mini_app_delete","required":false},{"id":"mini_app_edit","required":false},{"id":"mini_app_view","required":false}]},{"id":"periodic_task","actions":[{"id":"periodic_task_view","required":false},{"id":"periodic_task_edit","required":false},{"id":"periodic_task_delete","required":false}]},{"id":"task","actions":[{"id":"task_view","required":false},{"id":"task_edit","required":false},{"id":"task_operate","required":false},{"id":"task_claim","required":false},{"id":"task_delete","required":false},{"id":"task_clone","required":false}]}]},{"id":"common_flow","actions":[{"id":"common_flow_view","required":false},{"id":"common_flow_edit","required":false},{"id":"common_flow_delete","required":false}]}]}', '2022-04-04 06:38:06', '2022-04-04 06:38:06');
INSERT INTO bkiam.saas_system_config (pk, system_id, name, type, value, created_at, updated_at) VALUES (10, 'bk_sops', 'common_actions', 'json', '[{"name":"使用流程创建任务","name_en":"Create task by flow","actions":[{"id":"project_view"},{"id":"flow_view"},{"id":"flow_create_task"}]},{"name":"使用轻应用","name_en":"Use mini app","actions":[{"id":"project_view"},{"id":"flow_view"},{"id":"mini_app_view"},{"id":"mini_app_create_task"}]},{"name":"使用公共流程创建任务","name_en":"Create task by common flow","actions":[{"id":"project_view"},{"id":"common_flow_view"},{"id":"common_flow_create_task"}]}]', '2022-04-04 06:38:06', '2022-04-04 06:38:06');
